### ISSUE TITLE
Feature Request:  add command-line options (and HB inputs) to the log output

### ISSUE THREAD

**Issue by rhapsodians** [donmelton/video_transcoding#10]
Hi Don,

Just looking through 150+ transcodes from the last month from the bash scripts/new Ruby ones and would appreciate if you could include the command (and options) as typed in the resultant output log. It would be really useful to see what was run instead of reconstructing it from the HB summary.

Also, could the --dry-run output be included too? Both of these are really useful post-transcoding especially for those of us who retain the logs and historically look back to see what was run.

Thanks again for all the hard work and for sharing these with us.
Joe

**Comment by donmelton** [comment]
Joe,

Thanks for the feedback! 

No, I don't want to add `transcode-video`-specific content to the `.log` files. That's because they're not actually logs of what `transcode-video` is doing. They're HandBrake logs. And I don't want to make them different from any other logs generated by HandBrake or `HandBrakeCLI`. I considered the approach you suggest when I started the project, but quickly realized doing so would make it difficult for other tools to compare and parse the log files.

A better solution to your problem, since it seems you want both the command as typed and the command as parsed, is to save them during batch processing. It's fairly simple to take the "[Batch control for `transcode-video`](https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video) example script and modify it to do this.

Other than the commands, much of the information you're interested in can be mined from the `.log` files as is. And I'll consider that as a future feature for the `query-handbrake-log` tool.

I'll close this for now, but feel free to continuing comment here especially if you have questions about modifying the batch processing script.

**Comment by rhapsodians** [comment]
Hi Don,

Thanks for the reply - your comments about just having HandBrake output makes a lot of sense especially for parsing afterwards. I think the main reason I suggested it was to look back historically to see settings used or commands run. All of which can be deduced anyway from the output. The batch addition works and I had already started including something similar over the weekend. 

Thanks again for the work and for giving me a new hobby (re-transcoding and spotting-searching for further improvements) :-)

**Comment by donmelton** [comment]
Joe,

I'm glad the batch file trick is working for you. I may actually modify the sample script in the "README" file to include something like that.

And you are very welcome for that new hobby. Just be careful it doesn't become an obsession. :)
