### ISSUE TITLE
Titles 2, etc.

### ISSUE THREAD

**Issue by platonium** [donmelton/video_transcoding#100]
Hi, I’ve run into an issue where detect-crop and transcode-video don’t see titles last 1 on an .iso of Americas Test Kitchen.

The GUI versions of Make MKV and Handbrake all see the full number of titles.  While I can transcode via handbrake, the results unsurprisingly just don’t seem as good that way.

Thanks.

**Comment by donmelton** [comment]
@platonium When you write "last 1," do you mean the last title on that .iso image?

Please tell me you're mounting that .iso image into a directory. My tools do not take an unmounted image as input. But that's not a bug. It's by design.

Also, can you include diagnostic scan output from `transcode-video` here? Using a command like this:

```
transcode-video -vv --scan "/path/to/mounted-directory"
```

Thanks.

**Comment by platonium** [comment]
Thanks, Don, using your tool on an unmounted .iso image was indeed the issue.  Much obliged as always and happy Thanksgiving.

**Comment by donmelton** [comment]
@platonium Happy Thanksgiving! :)

**Comment by bronson** [comment]
Heh, this just tripped me up too. The output from scanning an ISO looks correct, except it has only one track:

```
+ title 1:
  + index 1
  + duration: 00:00:20
  + size: 720x480, pixel aspect: 8/9, display aspect: 1.33, 29.970 fps
  + chapters:
    + 1: duration 00:00:21
  + audio tracks:
    + 1, Unknown (AC3) (2.0 ch) (192 kbps) (iso639-2: und), 48000Hz, 192000bps
  + subtitle tracks:
```

It would have been easier for me to figure out if the output was complete garbage. :)

Thanks for filing this issue. I'm back on track.
