### ISSUE TITLE
Getting "mp4track not available" error

### ISSUE THREAD

**Issue by gingerbeardman** [donmelton/video_transcoding#109]
```
Scanning with mp4track...
/usr/local/bin/transcode-video: mp4track not available
```

Any ideas?

-vv log: http://pastebin.com/raw/husVYkjF

**Comment by donmelton** [comment]
@gingerbeardman I'm sorry but I don't know what I'm looking at here. Can you give me some context about what the problem is you're trying to demonstrate? Thanks.

**Comment by gingerbeardman** [comment]
I'm getting the error "mp4track not available" which I thought would be obvious, apologies. 

I understand this is a part of the package so I'm puzzled why transcode-video says it's missing? 

Take a look at the pastebin for the terminal output of -vv in my file, which also has the error. 

The screenshot is an alternative way for you to at some information about my file.

**Comment by donmelton** [comment]
@gingerbeardman Now I understand. I was focusing on the screenshot and didn't see your log file. Thanks.

OK, you're getting the "mp4track not available" error because... `transcode-video` can't find `mp4track` in your default `$PATH`. That's pretty straightforward and the only way that error message is produced. I suspect `mp4track` isn't installed correctly.

So, please try this command and tell me what happens:

```
mp4track --version
```

Thanks.

BTW, it appears you're still using HandBrake version 0.10.5. You might want to upgrade to version 1.0.0 which was released on Christmas. It is much, much better. See:

https://handbrake.fr/news.php?article=37

**Comment by donmelton** [comment]
@gingerbeardman Any update on that `mp4track --version` test I suggested?

**Comment by serkantueten** [comment]
had the same error on macOS Sierra. had to confirm the xcode license with "sudo xcodebuild -license". after that, I installed mp4v2 again with "brew install mp4v2". hope that helps.

**Comment by donmelton** [comment]
@serkantueten Thanks! Hopefully that's the same problem for @gingerbeardman too.

**Comment by donmelton** [comment]
@gingerbeardman Since I haven't heard from you in over a week, I'm going to assume this is resolved and close the issue. But if it's not, comment here to me and I'll re-open it.

**Comment by gingerbeardman** [comment]
I've not had time to try it, but I will assume the workaround from @serkantueten will work for me

**Comment by donmelton** [comment]
@gingerbeardman Cool. Let us know how it works and Happy New Year! :)

**Comment by gingerbeardman** [comment]
```
matt$ mp4track --version
-bash: mp4track: command not found
```

the fix from @serkantueten worked - thanks!
