### ISSUE TITLE
--burn-subtitle lang

### ISSUE THREAD

**Issue by lambdan** [donmelton/video_transcoding#121]
With `--add-subtitle` and `--add-audio` it's possible to specify an language as argument, like `--add-subtitle swe`. 
I would like the same for the `--burn-subtitle` option, making something like `--burn-subtitle swe` possible.

It obviously wouldn't need a multi argument option like `--burn-subtitle swe,eng` as you can't burn two subtitles on top of each other (or I guess you can but that wouldn't be good.)

I use the `--burn-subtitle` option quite frequently as I burn in the Swedish VOBSUB of my DVDs. Traditionally I have only selected the Swedish subtitle track in MakeMKV and then always doing `--burn-subtitle 1`, but now I got another sourced input file which has multiple subtitle tracks so for each video I've had to look up which track number is the Swedish one. Having `--burn-subtitle swe` would make it easier.

**Comment by donmelton** [comment]
@lambdan Thanks for opening this issue so I could comment about this feature on the record since I get asked about it from time to time.

I actually considered implementing this feature when doing language-based support for adding subtitle tracks. But burning subtitles by language has a _big_ semantic problem that I don't like. I didn't want to do it then for that reason and I don't want to do it now. Let me explain...

As you've already deduced, it doesn't make sense to specify multiple languages since you can't burn more than one subtitle at a time.

But you have the same problem with input files containing multiple subtitles in the same language. This situation is very common, especially with Spanish, Portuguese and Chinese language subtitles and with commentary tracks in various languages. And it's even _more_ common in English because there are often at least two subtitles, one plain and one in SDH (subtitles for the deaf or hard-of-hearing) format.

So, which track do you select? You can't just pick the first track because you're guaranteed to be wrong a non-trivial percentage of the time. And unpredictable behavior is not a good user interface design.

I don't like option selectors which are ambiguous. And that's what I mean by this having a big semantic problem.

I'm sorry there's not an easier way for you to automatically burn Swedish language subtitles with `transcode-video` alone, but implementing a feature like this definitely would never work predictably in a general-use case for everyone else.

If your ripped movies only have exactly one Swedish subtitle then you're much better off writing a shell script to find that track number for you and print it out for use in a wrapper script around `transcode-video`.

Believer it or not, this is exactly how I automatically add all my audio commentary tracks. I scan the input file first looking for any track with "Commentary" in the title and then generate the appropriate `--add-audio` options. And searching for, presumably, the first Swedish subtitle would be even easier.

If you want, I can write that script for you. Seriously, it's not hard and I would consider it preferable to adding a new feature. :)

I'll leave this issue open for now so you can comment. Thanks again!

**Comment by lambdan** [comment]
Ah I see, makes a lot of sense.

Maybe you could cause it to error & exit if there was two subtitle tracks of the same language, like you do when `--crop detect` gets two different values?

Otherwise, I can live without it. 
As I said, I usually just rip the Swedish track myself when I use MakeMKV, so I can just do `--burn-subtitle 1` but now I got some other input files where all subtitle tracks were present. 
Not a big deal as it is just this particular set of videos (not a very big set, and I have already gone through the effort of determining the tracks manually, and it actually turned out to be 9 for all of them so I just do `--burn-subtitle 9` in my batch script instead.)

(On the other hand I could also just add the subtitles instead of burning them, and let Plex burn them in on the fly. As they're just SD resolution it wouldn't be very CPU intensive on the server, and this is actually what I do for Blu-rays as I store those in "original MakeMKV-format" (I don't wanna burn them in on Blu-rays as those take way longer to transcode, usually have a very bad thin white font that is hard to read on light backgrounds and finding a plain-text version subtitle synced for the Blu-ray version of a movie is much more likely than finding one for a DVD version, in my experience.))

I just thought it would make sense to suggest as a feature as both `--add-audio` and `--add-subtitle` has it, but I also figured it's something you had already considered since it seemed like a pretty obvious feature to implement.

You don't have to bother writing that "auto find swedish subtitle"-script though, unless you really want to and is bored. 
(I would maybe like to take a look at that commentary track scanner though, if it's not too much effort. That sounds really useful.)

Thanks for responding.

**Comment by donmelton** [comment]
@lambdan OK, here's the script:

```
#!/bin/bash
#
# burn-subtitle.sh
#
# Copyright (c) 2017 Don Melton
#

die() {
    echo "$(basename "$0"): $1" >&2
    exit ${2:-1}
}

readonly input="$1"

if [ ! "$input" ]; then
    die 'missing input argument'
fi

if [ ! -f "$input" ]; then
    die "no such file: $input"
fi

readonly language="$2"

if [ ! "$language" ]; then
    die 'missing language argument'
fi

echo "$(HandBrakeCLI --scan --previews 2:0 --input "$input" 2>&1)" |
    sed -n '/^  + subtitle tracks:$/,$p' |
    sed -n 's/^    + \([0-9]\{1,\}\), [^(]*(iso639-2: '"$language"') .*$/--burn-subtitle \1/p' |
    sed -n 1p
```

Place it somewhere in your `$PATH` and use it like this:

```
transcode-video $(burn-subtitle.sh "/path/to/Movie.mkv" swe) "/path/to/Movie.mkv"
```

And, if there's a Swedish subtitle, it will add something like `--burn-subtitle 5` to your command line. The best thing is if there's no Swedish subtitle, it won't do anything. :)

I've also attached the script here:

[burn-subtitle.sh.zip](https://github.com/donmelton/video_transcoding/files/737149/burn-subtitle.sh.zip)

Enjoy and let me know what you think. Especially if there's a bug. :)

**Comment by lambdan** [comment]
Can't try that right now because I'm on Windows (or well I'm sure I could but not with my current setup.)
I can try on macOS tomorrow or later. But I'm sure it works as I assume you tested it.

Thanks, and I'll close for now.
