### ISSUE TITLE
Transcoding fails with little explanation

### ISSUE THREAD

**Issue by scavone** [donmelton/video_transcoding#122]
Before I get started, I first wanted to start off by thanking you for compiling these tools. They are awesome and provide such a great quality output with just the default settings. I'm currently using the newest dockerized version of your toolset provided by ntodd/transcode-video. The `transcode-version --version` command reports 0.16.0. Outside of the container, I'm running Docker 1.13.0 on an Ubuntu 16.04 desktop. I've successfully transcoded videos in the past using this method but I have one video which has failed to complete multiple times. When I run `transcode-video --no-audio --crop 0:0:2:0 -o "Crops/movie.mkv" "movie.mkv"`, it will run for a few hours but then I'll receive the following error...`/bundle/bin/transcode-video: transcoding failed: movie.mkv` with an error code of 255. When it crashes, it is always at a different % of the transcoding process as well.

A scan of the original file:
```+ title 1:
  + stream: movie.mkv
  + duration: 03:22:06
  + size: 1920x1080, pixel aspect: 1/1, display aspect: 1.78, 23.976 fps
  + chapters:
    + 1: cells 0->0, 0 blocks, duration 00:03:40
    + 2: cells 0->0, 0 blocks, duration 00:03:49
    + 3: cells 0->0, 0 blocks, duration 00:04:35
    + 4: cells 0->0, 0 blocks, duration 00:04:13
    + 5: cells 0->0, 0 blocks, duration 00:11:20
    + 6: cells 0->0, 0 blocks, duration 00:06:50
    + 7: cells 0->0, 0 blocks, duration 00:09:17
    + 8: cells 0->0, 0 blocks, duration 00:05:48
    + 9: cells 0->0, 0 blocks, duration 00:10:18
    + 10: cells 0->0, 0 blocks, duration 00:13:02
    + 11: cells 0->0, 0 blocks, duration 00:04:22
    + 12: cells 0->0, 0 blocks, duration 00:09:05
    + 13: cells 0->0, 0 blocks, duration 00:21:03
    + 14: cells 0->0, 0 blocks, duration 00:02:55
    + 15: cells 0->0, 0 blocks, duration 00:05:15
    + 16: cells 0->0, 0 blocks, duration 00:11:18
    + 17: cells 0->0, 0 blocks, duration 00:06:22
    + 18: cells 0->0, 0 blocks, duration 00:07:38
    + 19: cells 0->0, 0 blocks, duration 00:07:39
    + 20: cells 0->0, 0 blocks, duration 00:05:06
    + 21: cells 0->0, 0 blocks, duration 00:04:21
    + 22: cells 0->0, 0 blocks, duration 00:06:11
    + 23: cells 0->0, 0 blocks, duration 00:07:00
    + 24: cells 0->0, 0 blocks, duration 00:05:38
    + 25: cells 0->0, 0 blocks, duration 00:04:46
    + 26: cells 0->0, 0 blocks, duration 00:03:48
    + 27: cells 0->0, 0 blocks, duration 00:02:05
    + 28: cells 0->0, 0 blocks, duration 00:04:36
    + 29: cells 0->0, 0 blocks, duration 00:04:55
    + 30: cells 0->0, 0 blocks, duration 00:05:09
  + audio tracks:
    + 1, English (TrueHD) (5.1 ch) (iso639-2: eng)
    + 2, English (AC3) (5.1 ch) (iso639-2: eng), 48000Hz, 640000bps
    + 3, English (AC3) (2.0 ch) (iso639-2: eng), 48000Hz, 192000bps
    + 4, English (AC3) (2.0 ch) (Dolby Surround) (iso639-2: eng), 48000Hz, 192000bps
  + subtitle tracks:
    + 1, English (iso639-2: eng) (Bitmap)(PGS)
    + 2, English (iso639-2: eng) (Bitmap)(PGS)
```

Any thoughts or other information I could supply that might help?

**Comment by donmelton** [comment]
@scavone You are very welcome! And thanks for including a scan of your original input media file.

We first need to find out if the crash is happening in `transcode-video` or `HandBrakeCLI`. I suspect that latter but we need to confirm.

And what I really need is your `.log` file created by `transcode-video`. Can you attach or include that inline, please.

Also, I recommend adding the `-vv` option, or `--verbose --verbose` when diagnosing a `transcode-video` crash. This enables debugging information to printed to your console.

Thanks.

**Comment by scavone** [comment]
Absolutely...attached are the last few `.log` files. The 4th log has a newer version of the docker container running which was also my last attempt. I'll kick it off again with `-vv` and see if it shines any more light on the issue.

[movie.mkv.log](https://github.com/donmelton/video_transcoding/files/737291/movie.mkv.txt)
[movie.2.mkv.log](https://github.com/donmelton/video_transcoding/files/737288/movie.2.mkv.txt)
[movie.3.mkv.log](https://github.com/donmelton/video_transcoding/files/737290/movie.3.mkv.txt)
[movie.4.mkv.log](https://github.com/donmelton/video_transcoding/files/737289/movie.4.mkv.txt)

**Comment by donmelton** [comment]
@scavone Thanks! That was fast. :)

Unfortunately, these don't add much in the way of information about the actual cause of the crash itself. :( Your description is a very good one, it seems. Well done there.

The good news is that I'm pretty sure it's `HandBrakeCLI` that's crashing. Otherwise you would never get that error message from `transcode-video`. And the value of `255` is basically `-1`, which is a generic failure code.

BTW, is this movie of yours "The Godfather: Part II (1974)?" The duration, track layout and crop values are a dead-on match for my copy.

Speaking of its long duration, one possibility is that `HandBrakeCLI` or one of its many libraries can't handle the length of your movie in that Docker container.

Another possibility is that `HandBrakeCLI` or its "libav" library can't handle something about that particular Matroska MKV container. This has actually happened to me a few times and I've had to use `mkvmerge` to remux my movie to workaround this problem. Which is pretty simple to do with a command like:

```
mkvmerge -i input.mkv output.mkv
```

I know this isn't much help, but without a real crash log it's a hard problem to diagnose.

**Comment by donmelton** [comment]
@scavone BTW, that remuxing trick also works with `ffmpeg`, like this:

```
ffmpeg -i input.mkv -c:v copy -c:a copy -c:s copy output.mkv
```

I don't know whether `mkvmerge` or `ffmpeg` will solve this problem, but it's worth a shot.

**Comment by scavone** [comment]
@donmelton My desktop isn't exactly a transcoding beast (in case the logs weren't obvious enough, haha) so the program was still running this morning when i checked on it. I was thinking that processes running outside of the container might have caused `HandbrakeCLI` to choke previously, so this time I made sure that the container was the only thing running. The good news is that this round completed successfully!!

BTW, that detective work was spot on.

**Comment by donmelton** [comment]
@scavone Cool! You were obviously smarter than I was to try to make sure your container was the only thing running. I'll remember that suggestion if it comes up again.

OK, since this is working now I'll close the issue but feel free to continue commenting or opening other interesting issues as the need arises.
