### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by kford** [donmelton/video_transcoding#132]
Hi Don,
I have a perf question.  I've been using your scripts (love them) for years now on several machines running Linux and MacOS.

In recent years...
Transcodes on my T530 (Linux) were taking ~1.5 - 2h with a i7-3720QM (Quad Core) and spinny disk
Transcodes on my MBP were taking 1.5 - 2.25h with a i7-4870HQ (Quad Core) and SSD
Transcodes on my X1 Carbon (Linux) take ~7h, with a i7-6600u (Dual Core) and SSD

The X1 Carbon is the fastest processor of the bunch, but of course only Dual Core.  I expect the X1 Carbon to be a little slower because of this, but not 3-4x slower.

So my question is... Have you seen any common system configuration issues that have cause severe performance degredation? (very broad question I know).  I know I can tweak the transcoder, with --quick, or use the h264 preset system, but with the specs I'm using, I am really surprised to see 3x-4x slower than on my 4 y/o T530 so I thought I'd ask

Thanks in advance,

Kevin

**Comment by donmelton** [comment]
@kford Hi, Kevin! Good question. And that's for using my tools for so long! You're a veteran. :)

Most of the performance degradation you're seeing on your X1 Carbon is probably due to the lower number of cores. Seriously. Both HandBrake and x264 saturate and leverage multicore hardware better than any other software I've ever seen. This is why I don't buy anything with less than four cores anymore.

But that probably doesn't explain the whole slowdown.

First, run a simple tool like `top` and find out if you have any unexpected processes like daemons running in the background and sucking on your CPU.

Next, look very closely and that SSD and make sure it isn't prematurely fragmented or otherwise underperforming. If both your input and out are going to the same drive, then a slow drive is doubly problematic.

Finally, if you're reading your input files over the network, then measure throughput there, especially compared to your other hardware which is faster.

I'm sorry I don't have a quick fix or deeper insights here. But it's hard to make guesses at a distance. :)

Let me know how it goes!

**Comment by klogg416** [comment]
@kford Kevin,
Since the carbon series are ultralights, I would suggest that you might be hitting a thermal wall and seeing the CPU throttle back. If this is the case, the CPU would run flat out for a short while, hit a thermal limit, and then run at a reduced speed (although still 100% utilized) for the duration on the encode. 
A quick Google produces this check in Linux to see the dynamic speed you are running at.Tip: To monitor cpu speed in real time, run:$ watch grep \"cpu MHz\" /proc/cpuinfo
It looks like your stock speed should be 2600mhz, your boost speed (not likely to be achieved during encoding) is 3400, and anything less than 2600 is your old friend thermal throttling.
Curious to hear what you find,Kyle




On Wed, Mar 1, 2017 at 2:53 AM -0500, "Don Melton" <notifications@github.com> wrote:












@kford Hi, Kevin! Good question. And that's for using my tools for so long! You're a veteran. :)


Most of the performance degradation you're seeing on your X1 Carbon is probably due to the lower number of cores. Seriously. Both HandBrake and x264 saturate and leverage multicore hardware better than any other software I've ever seen. This is why I don't buy anything with less than four cores anymore.


But that probably doesn't explain the whole slowdown.


First, run a simple tool like top and find out if you have any unexpected processes like daemons running in the background and sucking on your CPU.


Next, look very closely and that SSD and make sure it isn't prematurely fragmented or otherwise underperforming. If both your input and out are going to the same drive, then a slow drive is doubly problematic.


Finally, if you're reading your input files over the network, then measure throughput there, especially compared to your other hardware which is faster.


I'm sorry I don't have a quick fix or deeper insights here. But it's hard to make guesses at a distance. :)


Let me know how it goes!

**Comment by donmelton** [comment]
@klogg416 Kyle, thanks. That's an excellent theory! And a very useful diagnostic suggestion.

**Comment by kford** [comment]
@klogg416 You nailed it.  I ran the watch cmd to look at CPU speed and found that shortly after the transcode began it went from 3600 -> 2600.  If I ran it longer it might go lower, I only ran for 10 minutes.  So now I have a sweet X1 Carbon that runs (regular work loads) like a cheetah and transcodes like a snail.

Anyway, thanks for the suggestion.  I guess there's a price to pay for this form factor.

**Comment by klogg416** [comment]
Sucks man, but not a terrible shock. The solution is clearly to build a new Ryzen box to ssh into and let it do the heavy lifting. :)






On Sat, Mar 4, 2017 at 1:11 AM -0500, "kford" <notifications@github.com> wrote:












Closed #132.
