### ISSUE TITLE
Making audio LOUDER

### ISSUE THREAD

**Issue by Bob-Collins** [donmelton/video_transcoding#133]
Is there a way to make the audio in the transcoded video, louder?  If so, what are the options to do so?

I ask because when I watch the transcoded video on my Roku through my TV, I have to double the volume on the TV.  I usually watch everything with the volume set at 16, and when I watch the transcoded videos I have to turn the volume up to about 32, so I was wondering how to increase the volume of the video itself?

NOTE: When I watch the DVD which these videos were ripped from, the volume is fine and doesn't need turned up.

Thanks in advance!

**Comment by donmelton** [comment]
@Bob-Collins A few questions: Are the audio tracks on these problem transcodings in Dolby Digital AC-3 surround format? Do you have a surround sound speaker system, i.e. more than just two speakers? And is your sound system -- either your TV or your receiver -- capable of decoding AC-3 format?

Before you try to amplify the audio gain in your transcodings -- which might be possible -- you should find out where the real problem is.

**Comment by Bob-Collins** [comment]
The problem is in the transcoding or in the Plex application, or the Roku.  The audio is AAC, and varies from mono to stereo tracks.  I have fed Dolby Digital 5.1 through to the TV, and it seems better in this regard, but the mono and stereo tracks are the ones giving me fits with the volume being so low when they are played back.

**Comment by donmelton** [comment]
@Bob-Collins Ah. OK, that's unusual. The reason I asked those questions is that when this happens to other folks it's usually AC-3 audio that's the problem. I suspect that might be, in a way, still the problem because the AAC has obviously been transcoded via AC-3 ripped from your DVDs. AC-3 tracks can have volume normalization embedded within them. I believe HandBrake honors that during transcoding.

Anyway, let's get to how you can raise the volume of those AAC tracks.

While there's not a command specifically to do this in `transcode-video` itself, you can pass a command through to `HandBrakeCLI` to do what you want using the `--handbrake-option` (or just `-H`) argument.

Here's a snippet from text output via `HandBrakeCLI --help`:

```
       --gain <float>      Amplify or attenuate audio before encoding.  Does
                           NOT work with audio passthru (copy). Values are
                           in dB.  Negative values attenuate, positive
                           values amplify. A 1 dB difference is barely
                           audible.
```

So, we should try using this option, probably with a value of `5.0` to start out. Here's how you would do that:

```
transcode-video --handbrake-option gain=5.0 "/path/to/Movie.mkv"
```

Obviously `5.0` might not be the correct setting for your needs. You'll have to experiment a bit.

And let me know how that works!

**Comment by Bob-Collins** [comment]
OK, since i have already transcoded the files once, can I run this command against the already transcoded files (running it a second time on the same file), or should I go back to the original files and rerun with all the other options used previously?

Also, if I can run it on the files already transcoded, will it keep the things done to the file on the first transcode (force bitrate and detelecine), or will they need to be specified again?

**Comment by donmelton** [comment]
@Bob-Collins Never re-transcode already transcoded files! Otherwise you degrade quality noticeably.

**Comment by Bob-Collins** [comment]
OK, I will go back to the original files I ripped and re-encode with the same options used the first time and add the handbrake option to increase the volume and let you know what I find out.  It will take a day or two before I will know anything .

**Comment by samhutchins** [comment]
As has been recommended to me by Don in the past,: make use of `--chapters` to only encode small portions of the video for testing this kind of thing ;-)

**Comment by donmelton** [comment]
@samhutchins Yes! Excellent advice.

**Comment by Bob-Collins** [comment]
I think that using the --prefer-ac3 to keep things AC3, might be better.  I am still experimenting to see what works best, it will likely be next week before I can decide which to do/use.

**Comment by donmelton** [comment]
@Bob-Collins OK, I leave this open until you let me know.

**Comment by donmelton** [comment]
@Bob-Collins BTW, I use `--prefer-ac3` now for all my transcoding and it works great with Plex and my various Roku devices even when they're not connected to a TV that can decode AC-3. The Plex Media Server just dynamically transcodes the surround audio -- and _only_ the audio -- to stereo and it still sounds good.

**Comment by Bob-Collins** [comment]
how do I use the normalize-mix option?  

I would like to try that as well, as some audio needs made louder, while others don't seem to need as much.  I am shooting to make them all the same so when I watch anything on the roku, I don't need to turn the volume up or down as I switch from show to show.

**Comment by donmelton** [comment]
@Bob-Collins The reason why HandBrake's `--normalize-mix` option doesn't work for AC-3 audio -- probably for the same reason that `--gain` doesn't work -- is that you're copying the AC-3 audio track from the original DVD rip instead of transcoding it. I should have realized that and warned you about it before. My apologies for wasting your time.

When a DVD movie contains surround audio, it's almost always in AC-3 format. The `transcode-video` tool won't re-transcode AC-3 if the input is already in AC-3 because doing so would degrade quality. This behavior is intentional and there's not an easy way to change it.

However, you can get the actual command and parameters that `transcode-video` uses to invoke `HandBrakeCLI` with the `--dry-run` option like this:

```
transcode-video --dry-run "/path/to/Movie.mkv"
```

You can then copy that output to a text editor, modify the parameters, and paste it back into your command prompt to execute the changed command.

The `--dry-run` copy-edit-paste process sounds crazy, but this way you don't have to figure out all the video options to replicate my special video ratecontrol system yourself, you just change the audio settings.

Let me know what you think.

**Comment by Bob-Collins** [comment]
You can close this out, I wound up using the --gain option with various amounts specified for the different shows.

Thanks!

**Comment by donmelton** [comment]
@Bob-Collins You are very welcome, sir! :)
