### ISSUE TITLE
parameters for mobile devices

### ISSUE THREAD

**Issue by navels** [donmelton/video_transcoding#137]
Thanks for the great tool!  I've been using it to batch transcode 1080p for my Plex server and the results have been fantastic.

Anyone have suggestions on targeting mobile devices?  Specifically I have an iPhone SE (1136‑by‑640‑pixel resolution at 326 ppi).  Not sure how what parameters to tweak to optimize for the phone.

Thanks!
Lee

**Comment by samhutchins** [comment]
- `--720p` because I don't see much point in encoding 1080p for an iPhone SE

 - `--mp4` to make sure it's compatible with the default video app, but that's up to you.

 - `--audio-width all=stereo`  because surround seems pointless on a phone to me, and the smaller file size from omitting it is worth it

**Comment by donmelton** [comment]
@samhutchins All excellent suggestions for @navels! Thanks for doing my job while I was AFK. :)

**Comment by navels** [comment]
Thanks!

**Comment by donmelton** [comment]
@navels I'm really glad the tools are working out for you. Are there any other questions we can help you with?

**Comment by navels** [comment]
I think I'm good, thanks!
