### ISSUE TITLE
Feature Request: Write to tmp file during transcode

### ISSUE THREAD

**Issue by alanwsmith** [donmelton/video_transcoding#14]
I'm transcoding a batch of mkv files. My process is:

1. Put a bunch of .mkv files in a directory.

2. Manually run `detect-crop` on each one to get the "transcode-video" recommendations.

3. Create a transcode.bash script in the source directory with a line for each transcode call. For example:
        
        #!/bin/bash
        
        transcode-video --mp4 --crop 0:0:0:0 PrettyGoodMovie.mkv
        transcode-video --mp4 --crop 132:132:0:0 AwesomeMovie.mkv
        # etc...

4. Run the script overnight to process as many movies as possible.

5. Stop the script in the morning when I have to go to work. 

6. Figure out which movie was only partially transcoded. 

7. Delete the partial file so the next time the script is run the full movie gets transcoded. 

---

My suggestion is to update the 'transcode-video' script to write the output file to a temporary location (e.g. "AwesomeMovie.mp4.tmp") during the transcoding. Then, when the transcoding is complete, rename it to its final name (e.g. "AwesomeMovie.mp4"). 

Aside from batch runs, this will also help avoid confusion for simple calls if the transcoding chokes or is stopped before finishing. It'll be evident by the fact that the file still has a temporary extension that the process didn't complete.

**Comment by alanwsmith** [comment]
I made a version that writes to a temporary file then does the rename at the end. It's here:

https://github.com/alanwsmith/video_transcoding/tree/transcode-to-tmp

Let me know if you're interested and I'll open a pull request.

**Comment by donmelton** [comment]
@alanwsmith Thanks for the suggestion and the work to implement your idea. Not everybody takes the time to do that.

However, this is not a feature I want to add to `transcode-video` or `convert-video` (since it would have to be done there, too, for consistency). Let me explain...

This seems to be an unnecessary complication and change for little benefit when you can already do this with the `--output` option and an extra line or two in your batch script. Here's a small modification to your own script that would get you the same behavior:

```
#!/bin/bash

mkdir -p Temporary
transcode-video PrettyGoodMovie.mkv --output Temporary/PrettyGoodMovie.tmp.mp4
mv Temporary/* .
transcode-video --crop 132:132:0:0 AwesomeMovie.mkv --output Temporary/AwesomeMovie.tmp.mp4
mv Temporary/* .
# etc...
```

Of course, that script would be even simpler and much, much less repetitive if you started with the "[batch control for `transcode-video`](https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video)" example in the "README" file.

Moving things around in the file system has to be done very carefully. I notice looking at your patch that you're not checking whether the temporary file you create already exists. Or whether the final output file name exists after transcoding completes. You would also need to handle that situation if it did.

Anyway, it's an interesting idea but not one I want to pursue.

Thanks again!

**Comment by donmelton** [comment]
@alanwsmith This what I get for writing that example code before morning coffee. :) Here's a better way to do that:

```
#!/bin/bash

mkdir -p Temporary
transcode-video --mp4 PrettyGoodMovie.mkv --output Temporary/
mv Temporary/* .
transcode-video --mp4 --crop 132:132:0:0 AwesomeMovie.mkv --output Temporary/
mv Temporary/* .
# etc...
```

This leverages the ability to specify an output directory, not a file name.

**Comment by alanwsmith** [comment]
@donmelton - I too was writing code before coffee. (I know better than to try to move a file before making sure it exists, but the brain was still booting up.)

Thanks for the bash code snippet. I'll definitely take that type of approach. 

As an aside, I'm right there with you on being careful when moving files. I make it a point to never make a tmp -> final_location move in anything other than the same directory to prevent potentially jumping across volumes. I work with a lot of feeds and rely on the final atomic move of the "first write to tmp then move to final location" patter so that other processes don't pick up half-baked files. Basically the same thing rsync does. So much of my day to day work deals with that that I default to it. Even when, like your tools, it's not really necessary. Old habits...

So, I completely understand not wanting to pursue it. Should you ever decide it's worth re-investigating let me know and I'd be happy to help.

Finally, allow me to say a quick thanks for putting taking the time to put these tools together. They are a pleasure to use.

Thanks!

**Comment by donmelton** [comment]
@alanwsmith Thank you, sir! You're exactly the kind of user that keeps me working on this stuff.
