### ISSUE TITLE
--scan should show which title is the main feature

### ISSUE THREAD

**Issue by schwa** [donmelton/video_transcoding#149]
I don't believe it's possible to display what track is considered the main feature until I try to transcode a video - would it be difficult to add that ability to display the main feature track on a --scan?

**Comment by donmelton** [comment]
@schwa The `--scan` option in `transcode-video` already designates the "Main Feature" track as long as `HandBrakeCLI` can detect that. BTW, my implementation simply dumps the output of the `--scan` feature built into `HandBrakeCLI` itself.

Or am I misunderstanding what you mean?

**Comment by dmbreakey** [comment]
I have a suspicion that the op is facing a similar problem I've run into; namely discs that deliberately manipulate the metadata to present dozens of similar-looking tracks, **none** of which will correctly encode all the way through because the metadata has been deliberately compromised. And even sneakier, a lot of them **start** out fine, to fool you into wasting time.

In this case, I don't think there is any guaranteed way of reliably identifying the main feature without evaluating the menu.

The trivial way around this is to use a software player, then navigate through the menu until you find it. Once you're confident the main title is actually playing, then just look at what track is playing.

Of course, you need to use a player that actually will **tell** you which track is playing... I've found VLC to be highly reliable on that mark.

**Comment by donmelton** [comment]
@dmbreakey Yes, this is a poor man's copy copy protection scheme used by some labels. I have a few Blu-ray Discs with hundreds of bogus playlists. The best way to deal with this leveraging teh Interwebs because someone else has usually figured out the correct track already.

**Comment by donmelton** [comment]
@schwa and @dmbreakey I'm closing this now because we're not getting any more traction on it. But feel free to continue commenting.
