### ISSUE TITLE
Transcode Folder + Overwrite Files

### ISSUE THREAD

**Issue by arijon** [donmelton/video_transcoding#153]
Hi Don,

I posted on the MGG Facebook about video transcoding and both you and Dave commented on my post. Thanks so much! I'm very excited about this script, though am quite new to the terminal. Quick question: is there a simple way to transcode a whole folder and have it write the output files to that same folder? Ideally it'd be even better if the original files could be overwritten by the new ones. Thanks!

**Comment by donmelton** [comment]
@arijon My apologies. I missed this earlier today due to traveling. Was I able to answer your question sufficiently on Facebook?

**Comment by arijon** [comment]
@donmelton No worries! I replied via Facebook. Best to continue the conversation there or here? :)

**Comment by donmelton** [comment]
@arijon Actually, it's probably best to continue the conversation here for the benefit of other users.

I'll paste in my answer from Facebook later so folks have some context.

So feel free to keep asking questions here.

**Comment by donmelton** [comment]
@arijon OK, it turns out it's not easy to paste out conversation from Facebook here. :) So either place works for me.

**Comment by arijon** [comment]
@donmelton either (or both) work for me, especially if users in both places can benefit from this conversation. :)

**Comment by arijon** [comment]
Here was my reply in FB:

@donmelton Thanks again for getting back to me, and please forgive my noob status with the Terminal, but this is what I get when I tried to use cd. Thoughts? 
![screen shot 2017-05-25 at 8 28 05 pm](https://cloud.githubusercontent.com/assets/28962067/26480619/1051c71c-4190-11e7-8ef7-e4703d0bdcce.png)

**Comment by donmelton** [comment]
@arijon And here was my reply to that from Facebook:

The `transcode-video` tool can only take input from a directory when that directory is a disc image, i.e. it's in the same format as DVD or Blu-ray Disc.

It appears the directory you're passing `transcode-video` is just a folder of media files, correct?

**Comment by arijon** [comment]
@donmelton Yes exactly!

**Comment by donmelton** [comment]
@arijon That's what I thought. OK, you need to process those as separate files either in a batch script or with a command line like:

```
transcode-video /Volumes/video-1/TV\ Shows/Fargo/Season\ 3/*.mkv
```

That works because `transcode-video` can handle multiple files at the same time. However, be advised that this is not always advisable since you can't provide different options for each file if that's required.

That's why I always recommend a batch script. You can find out how to create a batch script here:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

**Comment by arijon** [comment]
@donmelton it's working TYSM!!!

**Comment by donmelton** [comment]
@arijon You are very welcome. :)

**Comment by arijon** [comment]
@donmelton Hope all's well! Just taking another crack at this. I was wanting to play a video ripped from Blu-Ray on my iPad pro 10.5", but the letterbox at the top and bottom are quite pronounced. I tried to crop it with the default cropping you put in the tutorial, as well as the detect crop, but the letterbox doesn't go away. I'd be willing to sacrifice a bit of the sides if I could have a full-screen experience. Any thoughts of how to do this, or what would be the proper crop to go from BR to my iPad's screen? :) Thanks!

**Comment by donmelton** [comment]
@arijon I don't think you need additional cropping depending on which player you're using on your iPad. Most good players, e.g. [Infuse](https://firecore.com/infuse) and [VLC](http://www.videolan.org/vlc/), allow you to "zoom" in so that your video's shortest axis (either vertical or horizontal) fits tightly against the edge of the screen while the other axis is cropped. I'm not sure if the built-in "TV" app allows this but it should.

Also, I can't give you the cropping bounds without seeing your video first, which would likely be a legal violation. :)

**Comment by arijon** [comment]
@donmelton I was using DS Video. I'll give VLC a try. Thanks again!
