### ISSUE TITLE
Convert a TV Broadcast signal into a web streaming link

### ISSUE THREAD

**Issue by livetvcanada** [donmelton/video_transcoding#161]
Hi Don, 

I hope this message meets you well. 

I kindly have a request. My team and I built a web streaming platform for linear tv channels. Currently, we are discussing with a TV network company to offer its channel on our web platform. But they have a broadcast satellite signal, we need a web link in order for it to be available for streaming on a web browser. Basically, my question with the satellite signal, how can we convert it into a streaming link, would it be possible to assist in how to convert that? 

Look forward to your response. 

Kind regards 

George

**Comment by donmelton** [comment]
@livetvcanada Well, that's certainly a novel request. :) Unfortunately, it's not really my area of expertise or an appropriate usage my tools in this project. But, I suspect, it's the perfect job for FFmpeg.

I suggest you check out FFmpeg's "Steaming Guide" on their wiki here:

<https://trac.ffmpeg.org/wiki/StreamingGuide>

And you could simply search online for additional information here:

<https://duckduckgo.com/?q=using+ffmpeg+for+http+streaming>

If you would like, I can post this on Twitter and see if any of my many followers have suggestions as well. Let me know.

I hope that helps.

**Comment by livetvcanada** [comment]
@donmelton thank you. I think a simplified question would work on a 140 word limit lol - Look forward to any update you receive from your followers. Thank you.

**Comment by donmelton** [comment]
@livetvcanada Oh, I'll just link to this issue so they can comment. :) Stay tuned for that...

**Comment by donmelton** [comment]
@livetvcanada Hopefully I guessed your Twitter handle correctly. :)

**Comment by livetvcanada** [comment]
Yes, it's correct. thanks Don

**Comment by donmelton** [comment]
@livetvcanada Did you ever get any feedback on this via Twitter?

**Comment by livetvcanada** [comment]
Hi,

No we did not.

**Comment by donmelton** [comment]
@livetvcanada Dang. I was hoping someone out there was an expert.

I'm not sure how to proceed on this one because, as I mentioned, it's not my area of expertise. I'll probably close this since I don't think we'll ever resolve it here. I assume you're OK with that?

**Comment by metabaron** [comment]
Hello,

Have you found a solution to that problem? I might be able to help but it would require a bit more information such as how you transcode from satellite to a feed

**Comment by livetvcanada** [comment]
Hi,

Thank you. No we have not. What kinda information do you need?

**Comment by metabaron** [comment]
In order to help, the idea is to understand how you move from a satellite feed to some more "regular" feed we could work with (and when I mean we I'm not talking you and me :) ).
So: how do you acquire your satellite feed so far?

What you are trying to do here is first getting the satellite feed to something we can later encode to Web format (basically you are trying to do an OTT service based on satellite feeds ...)

**Comment by livetvcanada** [comment]
Hello Mathieu,

Thank you. I have attached the document for more information. We are trying
to work with our partner, Sony Movie Channel to get satellite broadcast
signal onto web format. We do not have any satellite. We are working with a
media partner to stream their TV content [which is broadcasted via
satellite] onto our web platform.

Regards

On Sun, Jan 28, 2018 at 9:31 PM, Mathieu Feulvarch <notifications@github.com

**Comment by metabaron** [comment]
I see. So the first thing you will need it to acquire the satellite stream (PS: that is what we do here at work - working for an ISP in Asia, taking care of the TV service).
I can imagine that you are doing it for a professional service right? Is $$ very sensitive or you guys can invest on proper hardware?

**Comment by metabaron** [comment]
Simple and easy for Linux with $$ being a problem, I would go: https://www.videolan.org/vlc/streaming.html

**Comment by livetvcanada** [comment]
Thank you. To answer your question,

Q: Is $$ very sensitive or you guys can invest on proper hardware?
Answer: At this point, we don't intend to invest on proper hardware.

Thank you for the link. Would the link enable us to convert the satellite
broadcast to Web format [HLS]?

**Comment by metabaron** [comment]
In case you were to invest properly: https://www.ateme.com/ would be my suggestion.

Lazy version (to test): https://wiki.videolan.org/Documentation:Streaming_HowTo/Streaming_for_the_iPhone/ which should work with a bit of adaptation 
That should work in your case without too much adaptation but that would not be ideal.

After, in term of "to the core", I would go with something around http://www.bogotobogo.com/VideoStreaming/ffmpeg_http_live_streaming_hls.php that idea. Why? Because ffmpeg is kind of a light / optimised VLC done to play around with video source, compared to VLC which is a player with transcoding capabilities.
Also, please read https://blog.twitch.tv/live-video-transmuxing-transcoding-ffmpeg-vs-twitchtranscoder-part-i-489c1c125f28 to get a better idea about it all and some more examples.
And the "bible": https://trac.ffmpeg.org/wiki/StreamingGuide

Exhaustive list of possible solutions I just found: https://github.com/sparks/rter/blob/master/docs/streaming.md

And to finish if you guys do not like Apache: https://docs.peer5.com/guides/setting-up-hls-live-streaming-server-using-nginx/

Keep me posted

**Comment by donmelton** [comment]
We haven't had any input on this in over a year so I'm going to close this now.
