### ISSUE TITLE
Don't crop 4:3 aspect ratio videos

### ISSUE THREAD

**Issue by joelvh** [donmelton/video_transcoding#163]
Hi there,

Just discovered this project and replaced some home-made HandBrake commands with this!

I've created a simple batch script that does several things, but primarily converts MKV to MP4 after MakeMKV processes a DVD.

From what I can tell, what would be really handy is if `video_transcoding` had an option to skip crop detection if the aspect ratio of the video is 4:3. In DVD terms, this means the video in question is likely an Extra Feature, where the main title is likely anamorphic.

What I do is run `handbrake.scan.raw_output.scan(/aspect\s+(\d+:\d+)/).flatten.first` and don't crop if it's 4:3.

Would this make a logical addition? (Maybe `--crop-exclude-aspect=4:3`?)

**Comment by donmelton** [comment]
@joelvh My apologies for not replying sooner! I got the notification last night when I was away but forgot to respond when I got back.

I'm glad my tools are working for you. Essentially they started out as my own hand-made scripts to wrap HandBrake. :)

As to your proposal, I'm not sure what you mean since the `transcode-video` tool doesn't apply any crop, detected or otherwise, by default. In other words, my default crop is always `0:0:0:0`. And I can't prevent `HandBrakeCLI` from doing even cursory crop detection while at the same time using it to query the input media---that's just how `HandBrakeCLI` works.

Or maybe I'm misunderstanding you?

**Comment by joelvh** [comment]
@donmelton by all means, that was a very quick reply!

Maybe giving a bit more context will help clarify my experience, and it could very well be that this is not a relevant use case because it is related to batching and not inspecting videos by hand and configuring the `transcode-video` command per video.

I had a DVD that was ripped to MKV with MakeMKV, and then my script went through each MKV in a directory and was configured to detect the crop and fall-back. This became an issue because extra features were 4:3 and some scenes were interspersed from the film, which were letterboxed. The crop detection saw those frames and cropped the video based on the letterbox frames, but this meant that the interview scenes, etc, also were cropped as well.

Unless I'm thinking about this wrong, what I did was check the aspect ratio and assume 4:3 means it's "fullscreen" interviews and don't want to crop. Otherwise, I do want crop detection to crop the other 16:9 video files. (The only scenario where 4:3 would be cropped is if it's a really old letterbox DVD and isn't anamorphic, but that's probably something I'd know when ripping the DVD.)

Thanks for your time!

P.S. Any batch-related projects you're considering including? I see your example script, but just wondering if it's a consideration. Happy to contribute!

**Comment by donmelton** [comment]
@joelvh Ah. I see what you mean now.

OK, this is yet another reason why `--crop detect` will never be a default behavior of my `transcode-video` tool. And every month I regret adding that feature because that's about how often someone opens an issue like this. :)

Here's the problem: both HandBrake and FFmpeg do a shitty job of detecting crops. At best, they get it right about 90-95% of the time. But when they're wrong, they're often horribly wrong. Which is why I recommend that you _ALWAYS_ manually review _ALL_ detected crops before you apply those values.

Even if I added the feature you suggested to prevent any cropping of 4:3 aspect ratio DVDs, that doesn't mean your automatically detected crops elsewhere---like the main feature---won't be wrong.

So, I won't add this feature to lull you into a false sense of security. :)

As to your postscript regarding batch-related additions, I have many that I've created myself. However, these are notoriously hard to generalize which is why I haven't added them to the current project.

For example, I have a script that detects commentary tracks and automatically adds them to the current transcoding job. But that script depends upon metadata that I added when the original track was ripped.

This is why I kept that example script simple. And you can probably now guess why the one "variable" behavior in that example focused on cropping. :)

**Comment by joelvh** [comment]
@donmelton Ah - yeah. I'm sorry - I should have thought to look at the closed issues!

I'm definitely taking the lazier approach, having the daunting task of ripping a large DVD collection I should have started this process with years ago. My approach is to check crops afterwards and fix the bad ones.

For batch processing, I can see a pipeline approach with some detection rules. But the inconsistencies across media, etc, make it a headache.

Thanks again, and sorry for the repeat question. Will contribute more productively in the future as I continue to play with `transcode-video`.
