### ISSUE TITLE
Extract Subtitle Argument?

### ISSUE THREAD

**Issue by steveowashere** [donmelton/video_transcoding#168]
Hello, 

I am finding in my workflow it's much easier for me to deal with external subs, rather than internal ones. My reasons are:

- Modifying internal subs requires the whole MKV to be re-transcoded(right term?) in order to remove or add them

- Plex doesn't like them. The Plex app on several of my smart TV refuses to play nice with internal subs. External subs work perfectly however. 

- For me personally, it's far easier to manage a library with subs that are external. For example I can do a simple 'ls' of my movies directory, and see if the MKV has an .srt file. Since i use Plex, i use their naming convention, which makes checking which of my movies have don't have subs super easy in a glance. 

- Plex handles forced subs for me. I don't like burning them in, because it gets messy when I switch back and forth between subs of different languages. 

So for these reasons (at least in my use case) it would be nice to have an argument such as '--extractsubs' that can extract subs (all formats). I believe the 'MKVextract tracks' command can do this. 

Thanks for all the hard work on this, this is by far one of the most useful things I have every stumbled upon.

**Comment by donmelton** [comment]
@steveowashere Thanks for using my tools and you are very welcome, sir! I'm glad they're working for you.

First, to address some of your issues:

* Removing, adding or manipulating subtitles in a MKV or MP4 container does _not_ require that the video or audio tracks be re-transcoded. So there's no quality loss or significant time usage in manipulating subtitles. This editing process is typically called re-muxing.

* If the Plex client application on your smart TV can't play internal subtitles but _can_ play external ones, then it's possible something in your setup is misconfigured. I use Plex all the time with several different clients—Roku, iOS, desktop, Web, etc.—and never have a problem with internal subtitles. Also, I would recommend verifying that your smart TV is not requiring your Plex server to dynamically re-transcode your video if your TV can't handle text overlays.

Second, the feature you're requesting is outside the scope of what `transcode-video` is for. And I don't want to add that behavior to an already complicated tool since it's likely such an implementation would require more than a single option.

You should use `mkvextract` from the [MKVToolNix](https://mkvtoolnix.download) utilities or `mp4subtitle` from the [mp4v2](https://code.google.com/archive/p/mp4v2/) utilities for manipulating subtitles. Those are the tools I use. And they have all the necessary options to do it right.

Thanks and I hope that helps.

**Comment by steveowashere** [comment]
Hi @donmelton , I appreciate the speedy reply. 

Thanks for the clarification on re-muxing vs. transcoding (still somewhat new and getting familiar with the terms) If subs can be added without affecting any of the other tracks, then that's a really good solution. Re-muxing still takes a little time, but by far much less than completely re-transcoding. 

After mentioned that my setup might be misconfigured, I did a little re-reading and I believe my problem is, that the server I was using, wasn't powerful enough to transcode (burn in) the subs on the fly during playback with Plex. (it also didn't help that the subs were bitmap, rather than text. Which from what I can read are more demanding to work with. Insert complaint about bitmap subs). I have a newer more powerful server that should be able to keep up, so I will test this theory soon. 

In any case, I will just setup a script using MKVtools to remux things as needed. Thanks for taking the time to reply!

**Comment by donmelton** [comment]
@steveowashere You are very welcome, sir! I'll close this for now but don't be shy about opening new issues or even commenting here again.
