### ISSUE TITLE
bad interpreter error after High Sierra update

### ISSUE THREAD

**Issue by joethezombie** [donmelton/video_transcoding#173]
Since upgrading macOS to High Sierra, I can no longer use the video_transcoding tools.  I get the error

`-bash: /usr/local/bin/detect-crop: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory`

Indeed, browsing to the Ruby versions reveals only 2.3.  Anyway I can fix this?  Sorry if this is an elementary question, I'm an end user and not really savy with Ruby.

**Comment by donmelton** [comment]
@joethezombie Thanks for the detailed information! I always appreciate that because you made it easy to diagnose this problem.

Whenever you do a major OS upgrade on macOS, e.g. Sierra to High Sierra, you need to remove and reinstall Homebrew and your Ruby Gems. Otherwise you get Ruby runtime errors and other even more annoying problems like this. I know that sounds like "reinstall Windows" and a big pain, but it's really necessary.

**Comment by donmelton** [comment]
@joethezombie I'm glad that worked out! And you are very welcome, sir! I'll close this now but feel free to continue commenting here or you can open another issue.

**Comment by goodydc** [comment]
@donmelton I was a little late to the game with upgrading to High Sierra, but received the same error message as @joethezombie. I resolved my issue, and am good to go now, but thought I would share what I discovered while troubleshooting (before I found this thread :-/).

1. High Sierra upgraded the ruby version from 2.0 to 2.3
2. As noted in the error message, _detect-crop_ was trying to use ruby 2.0, which no longer existed on my system
3. _gem install_ seems to insert _#!/System/Library/Frameworks/Ruby.framework/Versions/X.X/usr/bin/ruby -W_ at the top of your scripts, where X.X is the specific version number of ruby that was present when the gem was initially installed
4. The error message is generated because the old, fully-qualified path to ruby no longer exists
5. Additionally, the RubyGems Environment installation directory changed from _/Library/Ruby/Gems/2.0.0_ to _/Library/Ruby/Gems/2.3.0_, so ruby wouldn't find the previously installed gem anyway. This is also why _gem list_ no longer included video_transcoding as a local gem.

That's a long way of saying that your recommendation to reinstall the Ruby Gems after a major OS upgrade is the way to go. Perhaps you could add your recommendation to the FAQ, for future reference?

**Comment by donmelton** [comment]
@goodydc Thanks for the information!

That's a good idea. However, it might be better for folks to install Ruby using Homebrew instead of relying on the version which ships with macOS. That's what I do. I may change the README to include both strategies.

**Comment by goodydc** [comment]
@donmelton Good call. I didn't install Ruby using Homebrew since Sierra already included a version that worked with your tools.

Thanks for all your hard work on these tools! :-)

**Comment by donmelton** [comment]
@goodydc You are very welcome! And keep those useful comments coming.
