### ISSUE TITLE
Add documentation for handling when handbrake and mplayer disagree

### ISSUE THREAD

**Issue by alanwsmith** [donmelton/video_transcoding#18]
Running `detect-crop` on a movie returned the following:

    Results differ...

    # From HandBrakeCLI:

    mplayer -really-quiet -nosound -vf rectangle=1920:816:0:132 /path/to/Movie.mkv
    mplayer -really-quiet -nosound -vf crop=1920:816:0:132 /path/to/Movie.mkv

    transcode-video --crop 132:132:0:0 /path/to/Movie.mkv

    # From mplayer:

    mplayer -really-quiet -nosound -vf rectangle=1920:818:0:132 /path/to/Movie.mkv
    mplayer -really-quiet -nosound -vf crop=1920:818:0:132 /path/to/Movie.mkv

    transcode-video --crop 132:130:0:0 /path/to/Movie.mkv

The difference appears very minor in this case but it serves as an example. Are there details and/or a rule of thumb that can be added to the documentation on which `transcode-video` string would be the better choice?

**Comment by donmelton** [comment]
@alanwsmith This is a really good question and suggestion. Thanks!

I'm inclined to add this to the "[Using `detect-crop`](https://github.com/donmelton/video_transcoding#using-detect-crop)" section of the "README" file. It's not really appropriate for the built-in `--help` output since an explanation or guideline would be too long in that context.

Now, to answer the question for your specific disputed crop, the short answer is, "no."

I would at face value prefer the result from `mplayer`, `132:130:0:0`, since it's the least aggressive of the two choices. However, I would never make that choice without first reviewing both crop results. I've seen this go both ways which is why it just cannot be automated safely. And after running the tool over thousands of different inputs, it's clear to me that there is no "rule of thumb."

Which means that you probably will not like the documentation I eventually add for choosing between these disputed crops. :)

Anyway, I'll leave this issue open until I add this to the "README" file. Feel free to comment or add suggestions.

**Comment by alanwsmith** [comment]
@donmelton - Right on. Thanks for the explanation. I'll run both versions and take a look. (The curious part of my mind is interested to see if I can spot a two pixel difference.)

---

The README gets my vote for the locations too. That's where I looked initially. (It's so good, by the way, I never thought to look in the `--help` output.)

---

Some related thoughts:


1. I was looking in the detect-video sections and didn't notice the [Cropping][crop] section under [Using transcode-video][transcode]. A shout out from inside the detect-video sections that more info can be found under Cropping might help.
2. I find myself going jumping between the "Using..." and "Why..." sections for each of the tools. My instinct is that it would be easier to digest if you switched the outline from:

        - Rationale
          - Why transcode-video?
          - Why detect-crop?
          - Why convert-video?
          - Why query-handbrake-log?
        - Usage
          - Using transcode-video
          - Using detect-crop
          - Using convert-video
          - Using query-handbrake-log

    To:
    
        - transcode-video
          - Rationale
          - Usage
        - detect-crop
          - Rationale
          - Usage
        - convert-video
          - Rationale
          - Usage
        - query-handbrake-log
          - Rationale
          - Usage

3. A table of contents with links to each section would also be helpful.

I'd be happy to take a first crack at any of those if you like the direction.

[crop]: https://github.com/donmelton/video_transcoding#cropping
[transcode]: https://github.com/donmelton/video_transcoding#using-transcode-video

**Comment by donmelton** [comment]
@alanwsmith OK, I'll consider that. But the reason I, very intentionally, did it that way is to clearly separate the overview from the details. Which was a complaint with the old documentation. This means that with the new organization, the table of contents at the top could, for example, take you to just the "Usage" information.

**Comment by donmelton** [comment]
@alanwsmith My apologies that it's been almost a year and I still haven't added anything to the README about this. I suck.

But part of the reason for that is that I haven't liked any of my drafts so far of the explanation. And it's occurred to me that this really needs to be part of a FAQ document if not in the now too-long README itself. When I finally enable the Wiki here, I'll also create a FAQ.

In the meantime, I'm planning to add some new behavior to the `transcode-video` tool when the common code from `detect-crop` is invoked via `--crop detect`. See my explanation of the new behavior here:

https://github.com/donmelton/video_transcoding/issues/56#issuecomment-207827237

And let me know what you think. Thanks.

**Comment by donmelton** [comment]
@alanwsmith Sorry that took so long but I just added an example to the "README" document. Hopefully that's sufficient.
