### ISSUE TITLE
Convert-video does not recognized ffmpeg version on windows

### ISSUE THREAD

**Issue by CallumKerrEdwards** [donmelton/video_transcoding#19]
Kind what the title says really. Realised I had been outputting to MKV rather than MP4, so I tried to use the convert-video tool, but got the following error:

    convert-video The\ Imitation\ Game\ \(2014\).mkv
    ...
    /home/Callum/bin/convert-video: ffmpeg version unknown

## Environment 

* Script Version: 0.2.6
* Handbrake CLI version: Latest stable version 0.10.1 (2015030800)
* OS: Win7 x64 Service Pack 1
* Cygwin version: 2.0.1(0.287/5/3)
* Ruby version: ruby 2.0.0p598 (2014-11-13) [x86_64-cygwin]
* ffmpeg version N-70348-g9564375

**Comment by donmelton** [comment]
@CallumKerrEdwards D'oh! Sorry about that!

In order to fix this, I need a little more information about your particular build of FFmpeg. Please paste in the complete output of the following command:

```
ffmpeg -version
```

And it's very important that the output be formatted like code here, just like you did formatting the error output above.

Thanks.

**Comment by CallumKerrEdwards** [comment]
The output is as follows

    ffmpeg version N-70348-g9564375 Copyright (c) 2000-2015 the FFmpeg developers
    built with gcc 4.9.2 (GCC)
    configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --enable-decklink --enable-zlib
    libavutil      54. 19.100 / 54. 19.100
    libavcodec     56. 26.100 / 56. 26.100
    libavformat    56. 23.106 / 56. 23.106
    libavdevice    56.  4.100 / 56.  4.100
    libavfilter     5. 11.102 /  5. 11.102
    libswscale      3.  1.101 /  3.  1.101
    libswresample   1.  1.100 /  1.  1.100
    libpostproc    53.  3.100 / 53.  3.100

**Comment by donmelton** [comment]
@CallumKerrEdwards Thanks! BTW, where did you get this particular version of FFmpeg? Did you download it or build it yourself?

**Comment by CallumKerrEdwards** [comment]
I believe I downloaded it, at least I have the license and README etc all in a decent hierarchy, so it does match the "just throw it in there, I think that is on the path" folder.

**Comment by donmelton** [comment]
@CallumKerrEdwards OK, this will be harder to fix than I thought because the version string "N-70348-g9564375" doesn't have any semantic meaning that I can infer. It's not a Git revision number either. For all intents and purposes, it's a random number.

So, I'm not even sure if it's possible to fix this without completely disabling the version checking for FFmpeg. Which would be a bad idea.

I'll need to noodle on this awhile. Sorry about that. I thought this would be a quick fix but it's not. :(

**Comment by CallumKerrEdwards** [comment]
Should I try and find a different version of ffmpeg? As I said I am not certain of the providence of this version I have.

**Comment by CallumKerrEdwards** [comment]
OK I found the file providence. It is from here: http://ffmpeg.zeranoe.com/builds/. I believe that the string g9564375  is supposed to be a git related, as the file I downloaded was called  ffmpeg-20150301-git-9564375-win64-static.7z

**Comment by CallumKerrEdwards** [comment]
*UPDATE* I can find a better numbered version on the Previous versions page of the link above. Now I have ffmpeg version 2.5.2, and convert-video works. So there is a solution!

**Comment by donmelton** [comment]
@CallumKerrEdwards Silly me, I didn't consider that "g" was a prefix to the revision. :)

OK, I'm glad the other release version works for you. But I probably still need to make FFmpeg version handling more robust so I'll leave this open while I consider that.

**Comment by donmelton** [comment]
@CallumKerrEdwards Looking at the "N-70348-g9564375" string closer, it looks like this is derived from using the following command on a FFmpeg source tree checked out using Git:

```
git describe --tags --match N
```

While that now makes sense, the bad news is that there's no way to compare these "N" strings to see if one is older or newer than the other since neither number in the substring is an incremented value. And looking at the FFmpeg source code now, it seems that this isn't the *only* way to format an unreleased or development build of the product.

So, unless I want to parse the version numbers of the built-in libraries, e.g. "libavcodec," there's no way for me to reliably tell whether a particular version of FFmpeg is likely to be compatible.

Since it was relatively easy for you to find an actual release build of FFmpeg, and since no one else has reported this problem yet, I think it's safe to leave the code as is and simply require release builds.

I'll close this now but feel free to continue commenting.

And thanks so much for finding this issue! When I finally do get around to creating a Wiki for this project, I'll have to add this information to it.

**Comment by palitu** [comment]
I am in the throws of this issue :-/  i am just trying to find an appropriate linux apt-get package... bit of a nightmare really!

I'll post the results

**Comment by palitu** [comment]
Ok, so for ubuntu - 

download the stable static version, with a numeric version number (ie 2.8.5) from http://johnvansickle.com/ffmpeg/

them move all files into /usr/local/bin.

and probably apt-get remove ffmpeg!

this is probably worth putting on the readme.

cheers

**Comment by donmelton** [comment]
@palitu Is that the official URL for the stable static version on Ubuntu?

And yes, I'll consider adding that to the README.

Actually, I was considering removing the version restriction on FFmpeg just like I did on MPlayer recently. That's one way to solve this problem. :)

**Comment by palitu** [comment]
yeah i believe so.
