### ISSUE TITLE
I get this error when transcoding

### ISSUE THREAD

**Issue by itendtostare** [donmelton/video_transcoding#194]
Hi,

I'm currently working on transcoding my whole plex library from mkv to mp3, and stumbled on this beautiful jewel. Thanks for the hard work :) I m not super proficient with bash, here is the paste bin of the error, I trialed 2 files before this and all went smooth, but this happened : 
[Transcode error.pdf](https://github.com/donmelton/video_transcoding/files/1696977/Transcode.error.pdf)

**Comment by itendtostare** [comment]
command line used : transcode-video --mp4 --abr --quick "$1" ( shell script because I m running it from Hazel, as I want to automate the process in the future )

Also now that I m here, a slightly cheeky question, how do I make it so that the final file is saved into the exact same folder as the original file with Hazel? Cause at the moment it either ends up in usr/local or in the overarching folder of the original file

**Comment by donmelton** [comment]
@itendtostare Can you please attach that `.log` file here as text? You attached a PDF it's unfortunately  impossible to read that way.

**Comment by donmelton** [comment]
@itendtostare Also, can you just paste in the final error message that you're seeing here? That would save me a lot of time on diagnosing the problem. Thanks.

**Comment by donmelton** [comment]
@itendtostare Thanks! That's much easier to read now.

Unfortunately, this looks like some internal `HandBrakeCLI` error which I've never seen. Which is surprising because I've seen _a lot_ of them. Normally the muxer doesn't fail unless you run out of disk space.

Into which directory was this being transcoded?

BTW, by default `transcode-video` produces output in your current working directory. That would be the directory that you `cd` into when you invoke the command. But you can change that with the `--output` option.

Also, do any of your other TV episodes of that show have the same problem?

**Comment by itendtostare** [comment]
hei so...my video files are kept into a wireless external drive (4TB space) of which more than half is free now as I'm rebuilding it. I ran the command on my Mac through Hazel as I m currently testing it before using it on the whole external drive. Not sure if it uses my laptops space as well while transcoding. I ll try and run it again. And yes other episodes transcoded beautifully from terminal and using Hazel.

For the directory, I'll use this example: when I use Hazel I do the following:

1) look for mkv file in folder Volumes/Litha/TV Shows/Name of Show/Series/
2) run the shell script

When that happens Hazel copies the new file into Volumes/Litha/TV Shows
So then I m left with original file in the correct folder and new file some folders up.

Maybe is more of a Hazel problem? I m currently exploring the possibility of adding something at the end of the script to send it back to the same folder, but I would not have a set folder, as every episode will go in their respective Show - Season folder...

If I used the --output would my command look like

transcode-video --mp4 --abr --quick --output "$1" "Volumes/Litha/TV Show/Name of Show/Series

or can I specify "$1" again as output ? 

Thanks for all your help :)

**Comment by donmelton** [comment]
@itendtostare Yes, I suspect this is a problem with Hazel. Or your script. Or both. Here's what you need to do:

Run `transcode-video` on the same movie without using Hazel or your shell script. That way we take all those variables out of the way and simplify the problem domain.

Otherwise I don't think I can solve this for you. Sorry.

**Comment by itendtostare** [comment]
@donmelton as per your indication I tried again, and I m pretty sure the issue lies in the fact that my external HD lost connection while transcoding. Will have to transcode while having it wired to the laptop.

**Comment by donmelton** [comment]
@itendtostare Aha! OK, I suspect that's it. If you can confirm then we can close this issue.

**Comment by itendtostare** [comment]
yep all confirmed - thank you again, easier than I thought 👍

**Comment by donmelton** [comment]
@itendtostare No worries! Thanks for using `transcode-video` and providing feedback!
