### ISSUE TITLE
Multi language and subtitles

### ISSUE THREAD

**Issue by jasonwoerner** [donmelton/video_transcoding#196]
Just looking for some guidance here, as I'm doing something I would think is pretty common.

I have blu-rays of foreign language films. I want to rip and transcode such that I maintain both English language [dub] and foreign language tracks, and also the subtitles for the foreign language track. I'm having a lot of trouble accomplishing this with transcode-video's parameters. I'm looking to output to mp4. I understand the subs might be an issue. I'm actually having more trouble with the two audio tracks, which are DTS and must be converted.

How can I convert input like this:
video track
audio DTS A
audio DTS B
subtitle

to output:
video track
audio converted DTS to AC3 A
audio converted DTS to AC3 B
optional subtitle

Possible with transcode-video?

Thanks for any help!

**Comment by donmelton** [comment]
@jasonwoerner Yes, all this is possible with `transcode-video`, except for adding a Blu-ray Disc or DVD image-based subtitle track to an MP4 file. I'm sorry, but you can't do that. If you try to add one, `HandBrakeCLI` will just burn the subtitle into the video instead of adding it as an separate track. And I can't prevent that behavior.

So, You'll either have to convert that subtitle to a text format with another tool or you'll have to use MKV as your output file format. Because you probably don't want the subtitle permanently burned into the video.

Now to the command you would need to use. Let's assume the second audio track you want to add is actually audio track number `2`. And let's assume that you want that track to not only be in AC-3 format, but both AC-3 and AAC format, just like the main audio track is handled.

Let's also assume the subtitle you want to add is subtitle track number `1`.

Here's the command you would use for that:

```
transcode-video --add-audio 2 --audio-width 2=double --add-subtitle 1 "/path/to/Movie.mkv"
```

Why do you need that `--audio-width 2=double` option and argument? That's because any added tracks are, by default, transcoded in stereo AAC format. Setting the width to `double` means you get both AC-3 and AAC formats, again just like the main audio track.

Does that make sense?

**Comment by donmelton** [comment]
@jasonwoerner BTW, if you _only_ want the second audio track in AC-3 format, then just change that command to this:

```
transcode-video --add-audio 2 --audio-width 2=surround --add-subtitle 1 "/path/to/Movie.mkv"
```

Setting the width to `surround` means you get only AC-3 format if the original track is in surround format.

**Comment by jasonwoerner** [comment]
Don, your answer makes sense, and I'm very grateful to be able to get such a good one in such a short period of time. Much appreciated and, of course, thank you for the work you put into a terrific wrap-around tool.

**Comment by donmelton** [comment]
@jasonwoerner You are very welcome, sir! I'm glad it's useful to you. Let me know if you need further assistance.
