### ISSUE TITLE
Delete or Archive Original Upon Completion 

### ISSUE THREAD

**Issue by sixshooterz** [donmelton/video_transcoding#197]
Forgive me if this has been answered already, I’ve looked thru the Issues both open and closed and haven’t found an answer.

Is there an option to remove the original file(s) or move them to an archive folder upon successful transcoding or must this be done manually?

Thanks in advance!

**Comment by donmelton** [comment]
@sixshooterz I believe there might have been a discussion about this in an unrelated issue. But I can't find it either. :)

There is no option to delete original files and there never will be. Sorry. This is an idea fraught with danger, not to mention having security implications.

There is no option to archive original files because "archive" has too many meanings to engineer a one-size-fits-all solution. Sorry.

Really, both of these tasks are best taken care of in your batch file. And that is a file that I _intentionally_ do not provide. :) Although I do show you how to make one:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

Does this answer your question sufficiently?

**Comment by sixshooterz** [comment]
It absolutely does and makes 100% sense! I thought as much but it never hurts to ask. 

My mention of archive was a temporary holding place for the original file(s) in case upon inspection of the transcoded version there was an issue the original could simply be copied back. I’ll take a look at the batch control page. 

Thank you for such a speedy reply!

**Comment by donmelton** [comment]
@sixshooterz You are very welcome! And feel free to comment here or open another issue if you have questions about modifying the batch file.
