### ISSUE TITLE
Mixdown option doesn't pass through correctly

### ISSUE THREAD

**Issue by csvfx** [donmelton/video_transcoding#200]
Hi Don!

Have tried to use the --handbrake-option flag to pass through a custom mixdown setting but that doesn't seem to get processed by transcode-video correctly. It seems to interpret the mixdown value as the video source path.

Here's an example command using transcode-video 0.19.0, under mac OS 10.12.6

> transcode-video --handbrake-option mixdown 6point1 --dry-run --ac3-encoder eac3 /Volumes/video/Batch/2_Encode/SW1.mkv 
No such file or directory - 6point1

**Comment by donmelton** [comment]
@csvfx Thanks for writing such a clear problem report!

The reason why your command is failing is that you need an equal sign (`=`) between the name and value for the argument to `--handbrake-option`. Your command line should probably be this instead:

```
transcode-video --handbrake-option mixdown=6point1 --dry-run --ac3-encoder eac3 
```

I write "probably" because the `mixdown` option in `HandBrakeCLI` requires a comma separated list of audio tracks if you're including more than one track in your output. And by default, you are. So it's very likely that this, instead, would be the correct command line:

```
transcode-video --handbrake-option mixdown=6point1, --dry-run --ac3-encoder eac3 
```

But experiment a bit to find out and don't be shy about asking questions.

I hope that helps!

**Comment by donmelton** [comment]
@csvfx Did that fix the problem for you? If so, we can close this issue.

**Comment by csvfx** [comment]
All seems to work, thanks!
