### ISSUE TITLE
"No compatible video track" error when trying to use convert-video

### ISSUE THREAD

**Issue by j3d1c4nna** [donmelton/video_transcoding#207]
Hi Don

I've been using transcode-video and convert-video for many months now, with no issues. Today, though, I ripped a DVD using MakeMKV as normal and when simply trying to convert it to MP4 using convert-video, I received the error "No compatible video track". There doesn't appear to be anything weird or different about this rip, so I can't figure out what's wrong.

As a little test, I then tried using the ffmpeg -i command, and that seemed to convert the file to MP4 without any complaints.

Am I doing something wrong? Would there be any error logs I could provide, which might point me in the right direction?

Thanks so much for creating these awesome scripts, by the way, and also for the very entertaining podcasts.

All the best

Doug

**Comment by donmelton** [comment]
@j3d1c4nna By default, FFmpeg will transcode your video and audio. You have to explicitly tell it to copy each stream. And even then, it wouldn't copy MPEG-2 video into a MP4 output container.

I recommend just using the default options with `transcode-video`. If the quality doesn't seem good enough to you, try adding `--target big` to your command line to increase the video bitrate.

Using VLC is actually a good option since it's also available for iOS. There may even be a version of it for tvOS.

Let me know if you have additional questions. Otherwise we can close this issue.

**Comment by j3d1c4nna** [comment]
Hi

Thanks for the useful advice and for your time. Happy for the issue to be closed.

Regards

Doug

--
