### ISSUE TITLE
Video -> Video (mp4) with specific features

### ISSUE THREAD

**Issue by amitofry** [donmelton/video_transcoding#219]
Hey Don,

I pretty new to this world. I have a large number of videos (different formats) and I wish to transcode it into an mp4 files with the following features:

![image](https://user-images.githubusercontent.com/33203387/44954416-62334280-aeaa-11e8-84e5-6cd7e21ae786.png)

I have tried in the last few days various of commands but haven't managed to find a good command that will satisfy all or most of those features.

This is my best one so far :
transcode-video --mp4 --target 1200 --max-height 720 --max-width 1280 "video/a.mp4"

Which takes into consideration the bit rate and resolution but how can I integrate the other features also?

I would love to get your help.

Thanks in advance.

**Comment by donmelton** [comment]
@amitofry You don't really need to worry about those other features. And there's not a way to request those with `HandBrakeCLI` (and therefore `transcode-video`) anyway.

You can save yourself some typing by using the `--720p` option instead of `--max-height 720 --max-width 1280`, since it does the same thing.

Setting your target bitrate to `1200` Kbps for content that could be 720p is probably a bad idea. That will lower quality considerably. Bitrates that low are really only appropriate for DVD-sized content.

But if you want to hit a target bitrate reliably, try the `--abr` option to use my constrained average bitrate (ABR) ratecontrol system.

I hope that helps.

Any other questions?

**Comment by amitofry** [comment]
First of all thanks for your quick response!
As for the poor quality good to know but I'm OK with it.

I was wondering if there also a way to set the 1200 kbps as the upper-limit of the bitrate? (if for example, I have a video with a 1000 kbps it won't change it).

Thanks again.

**Comment by donmelton** [comment]
@amitofry Yes, there is a way to set a maximum bitrate with `HandBrakeCLI`, specifically via the x264 (or x265) encoding library that it uses. This is something that both my default and ABR ratecontrol system do, manipulating the value of `vbv-maxrate`.

My default ratecontrol system uses `vbv-maxrate` as the target bitrate, but it is designed to exceed that if necessary to maintain quality. My ABR ratecontrol system uses `vbv-maxrate` in a more traditional way and will never exceed that. However, changing `vbv-maxrate` without changing the target bitrate would cause significant quality problems for my ABR ratecontrol system.

If you want a hard upper limit on bitrate, you might want to use `HandBrakeCLI` directly rather than `transcode-video`.

**Comment by amitofry** [comment]
Ok, good to know.

And of course, thank you for this awesome tool!
