### ISSUE TITLE
External subtitle file: glyph issue

### ISSUE THREAD

**Issue by Nakda** [donmelton/video_transcoding#240]
Hi Don,

I have been using your tool recently and I love it so thank you very much for providing it.

Today, I wanted to transcode a bunch of videos while burning external subtitles (side-loaded .srt files). Here is an example of the command used:
`transcode-video --mp4 --target big --audio-width main=stereo --main-audio 1 --burn-srt "A Simple Favor (2018).srt" --crop 22:22:0:0 --chapters 1 "A Simple Favor (2018).mkv"`

The language used in those subtitles is french, so you can expect a bunch of accents. I found out that no matter the .srt encoding (sometimes ANSI, sometimes UTF-8) there is always something wrong with the burned subtitles: weird characters appearing as if the encoding was not properly set.

During the transcode, the log is full of: 
`[ass] Glyph 0x87 not found, selecting one more font for (sans-serif, 400, 0)`
`[ass] Glyph 0x93 not found, selecting one more font for (sans-serif, 400, 0)`

Thing is, when side-loading the .srt (no burning) while playing the original .mkv, the subtitles work perfectly. For the previous movies, I didn't encounter the issue but I did remember that all of them was embedding the subtitles natively (not side-loaded) so I tried to remux the MKV first (using mkvtoolnix) to get the external .srt in the .mkv before burning/transcoding.

Result: it works perfectly!

The only issue is that it takes some time to prepare everything with mkvtoolnix, so if you got any idea why I get weird results with the `--burn-srt` command, I would really appreciate ! 

Thanks.

Edit: I'm on Windows 10 (x64), running video_transcoding using binaries (not the Linux subsystem).

**Comment by donmelton** [comment]
@Nakda Sorry I took so long to respond! I've been AFK all day at the dentist.

You are very welcome and thanks for using my tools.

Wow. This is one strange issue. But sorry you're having this problem! It sounds like `HandBrakeCLI` is misinterpreting the format of your `.srt` file. Is it possible you could include it here as an attachment so I could take a look.

Also, which version of HandBrake are you using?

**Comment by Nakda** [comment]
@donmelton I thought I did answer but apparently not. Really sorry about that.

I'm using HandbrakeCLI v1.2.0 

Attached, the subtitle that was giving weird results. I got others if needed.

**Comment by Nakda** [comment]
@donmelton Don't worry, take your time.

On my side they are detected as "ANSI" most of the time, but some are UTF-8 and the same bug is occuring. For the ANSI ones, I already try a conversion to UTF-8 encoding: neither Notepad++ nor SubtitleEdit gave a good result. IIRC, some characters were displayed correctly after the conversion, but others started to bug.

If it matters, I did grab those subtitles from websites like opensubtitles.org.

Do you think it might be related to how video_transcoding or subsystems open and read the subtitles files? Because it only occurs when they are external, not when merged to the MKV.

I'm not skilled in this domain so sorry if it's a dumb question, but I remember I had to switch EOL conversion to Unix for the video_transcoding automation script to work (transcoding multiple movides through batch). I didn't try with the subtitles though, do you think it would change something?

**Comment by donmelton** [comment]
@Nakda That's not dumb, that's a good question! Yeah, you might want to switch to Unix line endings for HandBrake to be safe.

But speaking of HandBrake, let's take my `transcode-video` code out of the equation to see if the same thing still happens. (BTW, `transcode-video` never reads the external subtitle files directly.)

OK, if this is your command line:

```
transcode-video --mp4 --target big --audio-width main=stereo --main-audio 1 --burn-srt "A Simple Favor (2018).srt" --crop 22:22:0:0 --chapters 1 "A Simple Favor (2018).mkv"
```

... add the `--dry-run` option to it like this:

```
transcode-video --dry-run --mp4 --target big --audio-width main=stereo --main-audio 1 --burn-srt "A Simple Favor (2018).srt" --crop 22:22:0:0 --chapters 1 "A Simple Favor (2018).mkv"
```

Instead of beginning the transcode, `--dry-run` will output the command that will be sent to `HandBrakeCLI` instead. Just copy and paste that output back into your command line. That way we can see if this is a problem with `HandBrakeCLI` by itself.

**Comment by donmelton** [comment]
@Nakda OK, so the issue is within `HandbrakeCLI` itself and not `transcode-video`. That simplifies things at least.

I doubt the problem is the default font that `HandbrakeCLI` is using doesn't have the glyphs for French, rather the problem is that your external subtitle file contains invalid character codes that aren't in French or, possibly, any other Western language.

When I open your subtitle file in my text editor on macOS, it looks just as bad as when you look at it in Notepad++. Here's what I see for that same line:

```
Faciles ‡ Ètaler, mauvais pour le cúur.
```
 
Please note that there's a good chance that it won't be rendered correctly here either. :)

But there are all sorts of whacky characters in it. Making me believe that the subtitle file itself is somehow corrupt. Which means you'll probably have to edit it by hand to fix it.

And I still have no explanation for how VLC can display it correctly.

**Comment by samhutchins** [comment]
If I open it as an `Windows 1252` file in VSCode, it seems to be fine:

<img width="388" alt="screen shot 2019-01-17 at 09 44 01" src="https://user-images.githubusercontent.com/13986933/51309515-8009da00-1a3c-11e9-956d-a8cdd6b3d7dd.png">

Here it is re-saved as UTF-8:

[A Simple Favor (2018).srt.zip](https://github.com/donmelton/video_transcoding/files/2768002/A.Simple.Favor.2018.srt.zip)

**Comment by Nakda** [comment]
@donmelton
Interesting, on my computer it is displayed correctly in Notepad++, no
matter the encoding (ANSI or UTF8).
It is only when burnt in the video that the glyph is weird. When remuxing
with MkvToolnix first, no issue.

@samhutchins
IIRC, 1252 is labeled "Western Europe" in SubtitleEdit and it gave me the
same issue. I'm not on my computer at the moment, I'll confirm and provide
screenshots this evening.

Le jeu. 17 janv. 2019 à 10:46, Sam Hutchins <notifications@github.com> a
écrit :

**Comment by donmelton** [comment]
@samhutchins Thanks! Since Windows-1252 character encoding is a superset of Latin-1 and `latin1` is the default for `HandBrakeCLI` when it interprets `.srt` files, you would think it would all just work.

Maybe @Nakda should be passing something else as an argument to the `--bind-srt-encoding` option? And if so, do you know what that might be?

**Comment by samhutchins** [comment]
`transcode-video.bat --chapters 1 --burn-srt "A Simple Favor (2018).srt" --bind-srt-encoding cp1252`

Result:

![encoding](https://user-images.githubusercontent.com/13986933/51341484-51662080-1a89-11e9-851a-cb322f128979.PNG)

**Comment by Nakda** [comment]
@samhutchins Indeed, I can confirm that adding `--bind-srt-encoding cp1252` did the trick! Thank you very much.

I will detect the encoding of the subtitles and use the appropriate parameter from now on

**Comment by samhutchins** [comment]
@Nakda Awesome! Glad that worked. :-D

**Comment by donmelton** [comment]
@samhutchins No, you didn't misunderstand me. :) And thanks! You came to the rescue again.

@Nakda Whew! I'm also glad that worked. Shall we close this now?

**Comment by Nakda** [comment]
@donmelton Yes, closing it now! Thank again for the help, really appreciated :)
