### ISSUE TITLE
wrong h264 level for 720p 60 fps source

### ISSUE THREAD

**Issue by Mattrak** [donmelton/video_transcoding#241]
When using Transcode-video with 720p 60fps source, h264 level is not properly set to 3.2,  as recommended.

[1280x720-59,94.mkv.log](https://github.com/donmelton/video_transcoding/files/2730723/1280x720-59.94.mkv.log)

**Comment by donmelton** [comment]
@Mattrak Thanks for opening this! Sorry I took so long to respond to it but I'm actually sick today.

I'll take a look at it soon.

**Comment by donmelton** [comment]
@Mattrak OK, as near as I can tell from looking at the `.log`, `transcode-video` is passing `--encoder-level=3.1` to `HandBrakeCLI`. Which would be a bug because the input frame rate is greater than 30 FPS.

But I I need you to confirm that by adding `--dry-run` to your command line for that file and pasting the output in here.

If that's the case, then we need to figure out why my code isn't detecting the frame rate correctly.

Thanks.

**Comment by donmelton** [comment]
@Mattrak What a stupid I am! :) I forgot that I added code some time ago to always force the encoder level unless the user explicitly asks for a frame rate greater than 30 FPS. So, this is probably not technically a bug since `HandBrakeCLI` adjusted the level for you, but that may not be what you want anyway. If you do want output limited to 30 FPS (which might possibly be higher quality), then just add `--limit-rate 30` to your command line.

**Comment by donmelton** [comment]
@Mattrak Or (I forgot to mention), if you want to leave the output at 60 FPS and not get the warning from `HandBrakeCLI`, then you you can add `--limit-rate 60` to your command line.

**Comment by Mattrak** [comment]
Ok ! Thank you for your kind assistance

**Comment by donmelton** [comment]
@Mattrak You are very welcome! Are you OK with me closing this now?

**Comment by Mattrak** [comment]
Yes you can
