### ISSUE TITLE
Transcode subtitle to SRT instead of MOV_TEXT

### ISSUE THREAD

**Issue by Kraowe** [donmelton/video_transcoding#243]
When I transcoded a specific movie, I used: 
transcode-video --mp4 --quick -H optimize --no-auto-burn --add-subtitle all movie.mkv

Now, in Plex, they all show up as "MOV_TEXT" instead of SRT.

How do I just pass the embedded SRT files that was in the original, to the transcoded one? I dont want them to become MOV_TEXT. I would like to keep them as SRT.

Thanks in advance.
Btw, your scripts are awesome. Thank you for them.

**Comment by donmelton** [comment]
@Kraowe Sorry I took so long to respond. I've been AFK all day.

First, you are very welcome! Thanks for using my tools.

If your embedded subtitles show up as "MOV_TEXT" instead of "SRT" in Plex then that's to be expected since you're transcoding to MP4 format by using the `--mp4` option. There's no such thing as "SRT" tracks in an MP4 file. Such text-based subtitle tracks are supposed to be "MOV_TEXT" format in MP4 output. They should still work correctly. If not, then that's a bug in HandBrake or the FFmpeg library that it uses.

So, to keep your subtitles in SRT format, don't include the `-mp4` format and use the default MKV format for output. Plex can handle MKV just fine. I use MKV all the time myself with Plex.

I hope that helps. Let me know if you have additional questions or issues.

**Comment by Kraowe** [comment]
No worries, thank you!

Just one thing left, "output file exists", how do I specify output filename?

**Comment by Kraowe** [comment]
No worries, thank you!

You can close this issue.

**Comment by Kraowe** [comment]
The only issue I have now is that when using video_transcoding to make mkv instead of mp4, the AC3 5.1 track is #1, and AAC 2.0 is #2.

When making MP4´s, its AAC 2.0 first, then AC3. Which is what makes clients direct-play.

How can I transcode to mkv but have aac 2.0 as first track and ac3 second? I thought that was default.

**Comment by donmelton** [comment]
@Kraowe The AC-3 track comes first when outputting to MKV format because that's the common convention. Apple putting the AAC track first in MP4 output is actually the oddity. :)

But you can reverse the order of double tracks with the cleverly named `--reverse-double-order` option.

I hope that helps.

**Comment by Kraowe** [comment]
Thank you so much!

**Comment by donmelton** [comment]
@Kraowe No problem! :)
