### ISSUE TITLE
Question about using the E-AC3 codec

### ISSUE THREAD

**Issue by VideoMangler** [donmelton/video_transcoding#244]

**Comment by VideoMangler** [comment]
Hi Don,

Not really an issue, but a question. Now that HandBrake supports E-AC3 in a mp4 container, I was considering it for transcoded video to be used with my Apple TV 4K. I have quite a few Blu-Ray's with TrueHD or DTS-HD Master Audio content (in other words, lossless). It would be nice to use E-AC3, because as per the Dolby Digital Plus page on Wikipedia: "The DD+ extension bitstream is used on players that support it by replacing the rear channels in the 5.1 setup with higher fidelity versions, along with providing a possible channel extension to 6.1 or 7.1. The complete audio track is allowed a combined bitrate of 1.7 Mbit/s: 640 kbit/s for the AC-3 5.1 core, and 1 Mbit/s for the DD+ extension. During playback, both the core and extension bitstreams contribute to the final audio-output, according to rules embedded in the bitstream metadata."

Your comment in the now closed issue <https://github.com/donmelton/video_transcoding/issues/26#issuecomment-360996893> states that 640 Kbps would still be enough, but that would be inconsistent with the above from Wikipedia. Now the question is, what bitrate *would* be adequate?

I would have my workflow as follows: rip the BD with MakeMKV using the FLAC profile which results, then convert (let's say with HandBrake for now) to a mp4 using E-AC3 as the codec. (No idea what to do with the metadata in a TrueHD or DTS-HD MA stream though.) Bitrate 768? 1536?

(All this would be moot if the ATV would allow passthrough of such streams, but I digress ;) )

**Comment by donmelton** [comment]
@VideoMangler Great question! Well, most E-AC-3 found out in the wild (e.g. from torrents of Amazon content and such) is 640 Kbps. That's one reason I made that recommendation. The other is that E-AC-3 is more efficient at compression than AC-3 so you're packing more quality into the same bitrate.

Also, keep in mind that [Apple's live streaming guidelines](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices#//apple_ref/doc/uid/TP40016596-CH2-SW1) suggest 384 Kbps for 7.1 channels with E-AC-3. So you could go even lower.

But I wouldn't go higher than 768 Kbps because that might not be compatible with other devices. See [Roku's audio and video support documentation](https://sdkdocs.roku.com/display/sdkdoc/Audio+and+Video+Support) for details.

Does that answer your question?

**Comment by VideoMangler** [comment]
@donmelton Thanks for the quick reply! Yes, I see that the guidelines even recommend 192 Kbps for 5.1 Dolby Digital Plus! The only device I have is the ATV, and I'm happy to recode things in the event I get another hardware thingie. Having said that, I probably do some listening tests with different bit rates, to see how big the differences are. (Probably not that big so I will end up using 640, like I do now with plain old AC3, LOL.)

The remaining question is how the embedded metadata (about loudness etc. in streams like TrueHD and DTS-HD MA) are treated. Would you forego the intermediate step of saving a to be transcoded MKV first with a FLAC audio stream (using MakeMKV)? I'm not sure MakeMKV interprets such metadata... Or would you just go the normal Handbrake (perhaps using your script) route, that is, directly reading from the original TrueHD (or DTS-HD MA) stream? I assume Handbrake internally unpacks the stream as PCM anyway... couldn't find anything about it (or taking into account the embedded metadata) though in Handbrake's documentation (or ffmpeg for that matter...)

Thanks again!

**Comment by donmelton** [comment]
@VideoMangler Sorry I took so long to reply the second time! But I'm glad that helped.

I'm not sure how HandBrake interprets embedded metadata in lossless streams. It's only since the very latest version, 1.2.0, that HandBrake can even decode DTS-HD without just using the embedded lossy stream instead.

Also, I'm not sure how useful that embedded metadata actually matters when you're transcoding it. For example, the loudness adjustment in the older AC-3 format is notoriously unhelpful.

My recommendation is to continue converting all lossless audio streams to FLAC format. Mostly because all the tools out there, both transcoders and players, can read it without problems.

Does that help?

**Comment by VideoMangler** [comment]
It does, thanks!

I did some listening tests, and really the usual bitrates (for instance AC3 or E-AC3 at 640 Kbps) are just good enough. In some cases keeping everything in FLAC improves things a bit, but nothing earth-shattering. There's just not so many high quality surround mixes out there, and even then convenience pretty much wins...

If I find something about the internal workflow of HB or MakeMKV (in relation to metadata, PCM intermediates etc.) I'll report back. For now I'll settle on using E-AC3 as per your suggestions. (I heard that the Infuse App might be interesting for playing back MKVs directly including HD audio tracks, perhaps later more on that.)

Thanks again!

**Comment by donmelton** [comment]
@VideoMangler I assume E-AC-3 is working for you, so is it OK if I close this now?

**Comment by VideoMangler** [comment]
OK to close, thanks again!
