### ISSUE TITLE
Proposed documentation addition

### ISSUE THREAD

**Issue by vr8hub** [donmelton/video_transcoding#251]
The current documentation talks about hardware encoders, e.g. vt_264. You might consider including verbiage, however brief, referencing the Mac's VideoToolbox, since this is what the option is called in the latest (1.2) version of Handbrake. After I discovered the option in HB, I looked in this documentation for that option, and didn't find it. It was only by accident that I ran across the hardware encoder section. Just a thought. :)

Thanks so much for all of the work you've done on this. It's fantastic and greatly appreciated!

**Comment by donmelton** [comment]
@vr8hub Thanks for opening this issue! And you are very welcome for the tools. I appreciate you using them and giving me feedback.

However, I do describe hardware-based encoders and how to used them, with `vt_h264` as an example, in the FAQ section of the README document here:

https://github.com/donmelton/video_transcoding#what-about-hardware-based-video-transcoding

I placed it in the FAQ because it's one of the most asked question I get every week. :)

Unfortunately, I can't list all the encoders, software _or_ hardware, in the built-in documentation available via the `--help` option in `transcode-video` because there's no robust API for getting the list from `HandBrakeCLI`. But I do urge the reader to get the list themselves:

```
    --encoder NAME  use named video encoder (default: x264)
                      (refer to `HandBrakeCLI --help` for available encoders)
```

Or was there somewhere else you wanted me to mention it?

**Comment by vr8hub** [comment]
I know you mention hardware encoders. I _said_ you talk about them, and named where—the "hardware encoder" section. :) But I didn't know that when I did my initial search, because what I searched for isn't mentioned in that section, and I didn't know that section existed.

My suggestion was to mention VideoToolbox, however briefly, _in_ that section. That's what the Mac calls it, and it's what Handbrake calls it in the encoder list. When I searched the documentation, that's what I searched for, because that's what I read about elsewhere.

Calling it an encoder is more than I knew when I came looking. x264/5 are the encoders to me; VideoToolbox just does them in hardware instead of software. It's still x264/5. (I don't need a lesson in why this paragraph is so very wrong. :) My whole point is I didn't know enough to know to look for anything other than the option name.)

For someone like me, who isn't as steeped in this stuff as you are, who is simply looking to see if the tools support the VideoToolbox option that HB has, a mention of it would have been helpful. It doesn't have to be a paragraph or even a sentence; it can be a parenthetical word or two ("vt_h264, aka VideoToolbox"). That would have led me to the right place to read about what it was and what it was about.

I obviously don't need it anymore. I just thought it would be helpful for the next person(s) like myself who only knows enough to look for the option name used in Handbrake.

But, if you don't want to, you don't want to. It was just a suggestion. :) Thanks again!

**Comment by donmelton** [comment]
@vr8hub So sorry! I completely misunderstood.

OK, maybe I should list all of the hardware encoders by their proper names in that section then, not just VideoToolbox but Nvidia and such in case another person searches for it.

I'm planning on a release tomorrow. I'll see if I can get the change done by then. Otherwise I'll update the README after the release since the page is indexed anyway.

This is a great idea! Thanks for the suggestion.

**Comment by donmelton** [comment]
@vr8hub And, BTW, please keep the suggestions coming even if I'm a little dense at times. :)

**Comment by vr8hub** [comment]
Hah, no worries, I'm dense _all_ the time! Thanks for considering it; hopefully it will help the next person.

**Comment by donmelton** [comment]
@vr8hub Here's how I plan to rewrite that section of the FAQ:

* * *

### What about hardware-based video transcoding?

Hardware-based encoders, like those in [Intel Quick Sync Video](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video), are often considerably faster than x264 or x265. Some are available in recent versions of HandBrake.

Check the output of `HandBrakeCLI --help` to find out if your platform has any of these video encoders available:

Platform | H.264 encoder | HEVC encoder
--- | --- | ---
Intel Quick Sync Video | `qsv_h264` | `qsv_h265` and `qsv_h265_10bit`
AMD Video Coding Engine | `vce_h264` | `vce_h265`
Nvidia NVENC | `nvenc_h264` | `nvenc_h265`
Apple VideoToolbox | `vt_h264` | `vt_h265`

You can try hardware-based transcoding now using the `--encoder` option. On macOS, select the Apple VideoToolbox H.264 encoder this way:

    transcode-video --encoder vt_h264 "/path/to/Movie.mkv"

You can also use the `--target` option with these encoders.

* * *

Let me know what you think.

**Comment by vr8hub** [comment]
Perfect! The key is to have both things that people might search for. The HandbrakeCLI help says vt_h264/5, but the UI says h.264 (VideoToolbox). Us neophytes don't know those are the same until we read more, but we can't read more if we can't find what we're looking for. This lets us search for either one and find out about the other.

Thanks for the quick turnaround!

**Comment by donmelton** [comment]
@vr8hub Agreed! Your SEO instincts are much, much better than mine. :)

The change is in and the update has been released. Thanks again!
