### ISSUE TITLE
Add fallback-crop minimal documentation to ReadMe section of detect-crop

### ISSUE THREAD

**Issue by JMoVS** [donmelton/video_transcoding#266]
As some people might still use detect-crop separately, I'm assuming they might also want to know the "minimal" option of the detect-crop facilities added to the Readme. So as referenced, I'm opening this issue now.

_Originally posted by @donmelton in https://github.com/donmelton/video_transcoding/issues/255#issuecomment-468838581_

**Comment by donmelton** [comment]
@JMoVS Thanks! I'll draft something today.

**Comment by donmelton** [comment]
@JMoVS OK, how does this read as an addition to the "Cropping" section of the "README" document after mentioning that `--crop detect` can fail?

* * *

Which is why you can select a fallback behavior using the `--fallback-crop` option when that happens, choosing `handbrake`, `ffmpeg`, `minimal` or `none` as its argument:

    transcode-video --crop detect --fallback-crop minimal "/path/to/Movie.mkv"

The `minimal` argument is perhaps the most useful behavior since it determines the smallest possible crop values by combining results from both `HandBrakeCLI` and `ffmpeg`.

**Comment by JMoVS** [comment]
if it were for british spelling, I'd write "behaviour" but aside from that, 👍

**Comment by donmelton** [comment]
@JMoVS OK, that live in the "README" now. Thanks, again!

**Comment by platonium** [comment]
Dear Don and the Transcode Gang,

Thank you so much for minimal and your hard work.

Best,
Plato

Sent from my iPhone

On Mar 4, 2019, at 2:04 PM, Don Melton <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #266<https://github.com/donmelton/video_transcoding/issues/266>.

**Comment by donmelton** [comment]
@platonium You are very welcome! I'm glad you like it.
