### ISSUE TITLE
Add Video Transcoding version number to video metadata

### ISSUE THREAD

**Issue by martinpickett** [donmelton/video_transcoding#272]
As @khaosx mentions in [this comment](https://github.com/donmelton/video_transcoding/issues/271#issuecomment-471576638) it is possible to add the Video Transcoding version number to the metadata of a video. I would find this a useful addition to Video Transcoding as my current method for keeping track of which videos were encoded with which version is ... not good.

If I am honest, I would love to have all the Video Transcoding arguments that I used, stored in the video metadata, but just the version number would be a huge improvement on where I am now.

**Comment by donmelton** [comment]
@martinpickett I keep all my `.log` files around and my videos organized by versioned folder name so it's easy for me discern the origin. But 1) I'm a crazed anal-retentive and 2) I can see how that might not work for everybody else. :)

So I will consider this request!

Even though it's really @khaosx making my life more complicated again. :)

I would love to get some feedback on this, too. Plus, I need to find out if embedding the version in MP4 output is possible using `mp4track`.

Also, I'm inclined to make this behavior an option rather than the default. Not sure what to call it, though. And if we did make this the default behavior then we need a way to disable it with an option. So we'll need to come up with a name anyway.

**Comment by khaosx** [comment]
I like to keep you on your toes, @donmelton. 

@martinpickett I really wish that we could add a comment with mkvpropedit. I tried this morning and that's a non-starter, at least as far as I can tell. You might be able to add an attachment or a selector modification, but you'd have to gen an XML file first.

**Comment by martinpickett** [comment]
I am not great at this sort of stuff, but `--store-version` is the first thing that came into my head for an argument name.

I confess that storing the log files in the manner you described is quite a nifty solution, and one I am annoyed I did not think of myself.

@khaosx, I am way out of my depth here. I have never used mkvpropedit and have no idea what a "selector modification" is, so I am not sure how much help I can be.

**Comment by donmelton** [comment]
@martinpickett @khaosx OK, after much experimentation with `mkvpropedit` I have to agree with Kristopher that there's no way to add a simple top-level property on a file. :(

I can certainly replace the `writing-application` property but that contains the HandBrake version so I don't think that's right approach.

And an attachment is unwieldy since you would have to extract it to determine the version. Plus, there would be no way do this for MP4 files.

So adding appropriate metadata to the video file is not really possible. Sorry about that. :(

As for `.log` files, I don't want to modify them since they only contain output from `HandBrakeCLI` itself and my tools, other tools and even the HandBrake development team when bugs are submitted want them to be pristine.

Again, sorry about that. :(

**Comment by khaosx** [comment]
@martinpickett 

> An alternative solution to my real problem (keeping track of what video files were encoded with which version of Video Transcoding) would be to include the Video Transcoding version number in the log file.

Take that thought a step further and you've got a roll your own solution that I think we can help with. Make yourself a text file with the version of the gem that you're using, and make some notes about what settings you're using. Then you can install mkvpropedit (which, if I recall, should already be installed as part of the tools that are pre-reqs for Don's tool).

At that point, you only need to execute the following:

`mkvpropedit "FILENAME" --edit info --set "muxing-application=vtp_0.25"`

As long as it matches the version you notate in the text file, you've got a record of what settings you were using (in general) when that version was active. I can help you walk your way through this if need be.

> @khaosx, I am way out of my depth here. I have never used mkvpropedit and have no idea what a "selector modification" is, so I am not sure how much help I can be.

We're all swimming in the deep end here. The good news is that everyone here brings different flippers to the pool!

**Comment by donmelton** [comment]
@khaosx D'oh! Yeah, you can definitely repurpose the `muxing-application` property with that. It's not what they intended, but what the heck. :)

@martinpickett But, in the end, it doesn't matter which version of `transcode-video` you used. Because the important information is your version of `HandBrakeCLI`. And what encoding parameters were passed to it. This is because `transcode-video` is just a wrapper.

The good news is that all of this information is available with MediaInfo, the "Writing application" and the "Encoding settings".

**Comment by martinpickett** [comment]
I have done some playing around and succeeded in editing the `mixing-application` property as per @khaosx instructions.

Most of the time I use a wrapper script on top of Video Transcoding, so I am re-writing this wrapper script to include saving the Video Transcoding version number.

@donmelton I am content with modifying my wrapper script, plus the lack of comments from other users of Video Transcoding suggests that this is a niche feature, so please feel free to close this issue. Thank you and @khaosx for the quick and thoughtful responses to my query and for producing such a wonderful tool in the first place.

**Comment by khaosx** [comment]
@martinpickett You're welcome, and well done! You're a step ahead of me, as I haven't finished putting that change into my script.

**Comment by donmelton** [comment]
@martinpickett I'm glad @khaosx was there to help when my brain was stuck in neutral. :) Seriously, Kris, thanks again!

I'll close this issue now, Martin, but I have enjoyed our conversation here! If you would like to join myself, Kris and other contributors and commenters, I'd be happy to invite you to our Slack workspace for Video Transcoding. Just send me your email address and I can send you back an invite from Slack. The best way to do that is via my email and you can "deduce" my address on this page: https://donmelton.com/contact/

Thanks again!
