### ISSUE TITLE
Can't seem to get to work after updates

### ISSUE THREAD

**Issue by PhilStollery** [donmelton/video_transcoding#277]
/Users/phil/.rbenv/shims/transcode-video: line 21: /usr/local/Cellar/rbenv/1.1.1/libexec/rbenv: No such file or directory

I have Ruby 2.6.2 - when I first ran transcode-video it complained and said it needed 2.3.0 - so I used rbenv to switch ruby versions.

Then I got the above error - looks like rbenv has broke it. I've uninstalled and installed. Any other ideas?

**Comment by donmelton** [comment]
@PhilStollery I'm sorry you're having this problem and I'll see what I can do to help.

First, I'm not sure why `transcode-video` would say that it needed Ruby version 2.3.0. It should only require 2.0 or later and it doesn't even have an error message for that. Your Ruby interpreter must have made the complaint. Although I've never seen anything like that.

Also, line 21 in `transcode-video` is the beginning of the `about` function. So I don't know why that would cause an error either.

In order to help and not make things worse, I need to know more about your OS and Ruby configuration. Obviously you're running macOS but, for example, which version?

Could you execute the following diagnostic commands in a `Terminal.app` window and paste the results here:

```
echo $PATH

which ruby

ruby --version

gem environment
```

Also, I assume you installed and then removed `rbenv` using Homebrew? If so, did you also install the new Ruby version with Homebrew?

Thanks and sorry I don't have a more helpful answer right away.

**Comment by PhilStollery** [comment]
Please don't spend any time try to work this out if it's environmental. I'll try and get my system back to something. I'm using fish so it might be that?

...

Uninstalled and removed rbenv and all now works. Thanks for all your hard work on this Don. You are a generous genius.

**Comment by JMoVS** [comment]
Also check the rbenv maybe with

„Which rbenv“

And run „brew doctor“, maybe there are some stray symlinks

**Comment by donmelton** [comment]
@PhilStollery You are very welcome, sir, and I'm glad it's all working for you now.

Please don't hesitate to comment again here if you have another problem or even open a new issue. We want to make sure `transcode-video` is always working for you.
