### ISSUE TITLE
Multiple Inputs Without Using Batch

### ISSUE THREAD

**Issue by jameslmcdonald** [donmelton/video_transcoding#295]
I know you recommend batch processing for multiple inputs, but transcode-video can handle multiple inputs.

I do not see anything under that section or --help that explains how to.

How do you add multiple inputs without the batch?

Thanks!

**Comment by donmelton** [comment]
@jameslmcdonald Good question! If you look carefully at the `--help` output, it shows this:

```
Usage: transcode-video [OPTION]... [FILE|DIRECTORY]...
```
The `...` (ellipses) after the arguments indicate that multiple options or inputs can be specified on the command line. This is a common Unix idiom.

So you can simply do something like this:

```
transcode-video first-video.mkv second-video.mkv third-video.mkv
```

But keep in mind that any options you user are applied to all of the inputs.

Does that answer your question?

**Comment by jameslmcdonald** [comment]
Yes and No

Right now, this is what I got

transcode-video --m4v --crop detect --fallback-crop minimal --audio-width all=double --avbr --quick --no-log “/path/to/movie.mkv”

I want and know the options will be the same for each movie.  But I am having trouble applying what you are suggesting.  Do I do the path to each movie?  Do i put them in the same folder?

I am kinda new to this, so I apologize if I am a little slow.

Thanks!

**Comment by donmelton** [comment]
@jameslmcdonald Sorry I took so long to reply.

Just do this:

```
transcode-video --m4v --crop detect --fallback-crop minimal \
--audio-width all=double \
--avbr --quick --no-log \
“/path/to/first-movie.mkv” “/path/to/second-movie.mkv” “/path/to/third-movie.mkv”
```

Please note that I'm using the line continuation character (`\`) there to make this easier for you to read. You can take that out when the command is all on one line.

Does that help?

Also, you really shouldn't use the `--no-log` option since if you run into a problem, you'll have to re-transcode the whole movie just to diagnose what went wrong.

**Comment by jameslmcdonald** [comment]
That helped tremendously! Thank you so much.

I have a brain pick question for you. Your older version was 5,000 kbps for 1080. What made you up it to 6,000 kbps?

Thanks again.

**Comment by donmelton** [comment]
@jameslmcdonald Sorry I took so long to respond! I'm glad that worked for you. I changed the target bitrates based on subjective quality analysis and also to be bit closer to targets suggested by Apple and others.

I'll close this issue now since it's resolved, but feel free to continue commenting here or opening new issues.
