### ISSUE TITLE
Transcode-Video Fails if there are more than 100 tracks. 

### ISSUE THREAD

**Issue by asheimo** [donmelton/video_transcoding#304]
In this Scenario I was Transcoding Harry Potter and the Chamber of Secrets Bonus Disc, There are 158 tracks (most probably garbage but still) when referring to the directory for transcoding i.e. K:\Video\Harry Potter and the Chamber of Secrets Bonus Disc\ * (not a real space before the asterisk, had to add for formatting here in the request) the first track works the second fails. I removed that track and tried again, the first 10 tracks worked then the job failed again. After deleting many files one at a time and getting failures I moved all the files over 100 to a different folder. After doing that the job would run without issue.

I have made sure everything is up to date. I am running on windows 10. I do not know for sure if this is Transcode-Video itself or the command interpreter having issues.

**Comment by asheimo** [comment]
I should probably add the way the title is formatted; HARRY POTTER AND THE CHAMBER OF SECRETS_t100.mkv, ones that work are; HARRY POTTER AND THE CHAMBER OF SECRETS_t74

**Comment by platonium** [comment]
I have run into the same issues in the past.  It’s not the tools.  This is a copy protection feature.  There’s a good post on the makemkv forum on this: https://www.makemkv.com/forum/viewtopic.php?t=16791.  If you happen to be using makemkv, you can also backup the entire BD if you are in a hurry, and then figure out the details later using the backup files which will parse more quickly than the physical disk.  If it’s a DVD, I don’t believe that makemkv offers DVD backup: https://www.makemkv.com/forum/viewtopic.php?t=17844.


On Dec 6, 2019, at 7:09 AM, asheimo <notifications@github.com<mailto:notifications@github.com>> wrote:


I should probably add the way the title is formatted; HARRY POTTER AND THE CHAMBER OF SECRETS_t100.mkv, ones that work are; HARRY POTTER AND THE CHAMBER OF SECRETS_t74

**Comment by donmelton** [comment]
@asheimo This is actually not a bug. It's a side effect of the way the `*` character is expanded to full multiple path names on the command line. And it's a very platform- and shell-specific effect. It also depends on how many path names are expanded. This is because various shells have limits on the number of characters that can fit on a single command line. Go figure.

Anyway, this is why I don't recommend using this feature. Instead, I recommend that when processing multiple files, that you use a batch file. See this section in the README document for an explanation on how to do that:

https://github.com/donmelton/video_transcoding#batch-control-for-transcode-video

Does that help?

**Comment by donmelton** [comment]
@asheimo To be clear, the "passing multiple files on the command line" feature often works fine if you're only doing a few files at a time. Otherwise it's rather unpredictable.

**Comment by asheimo** [comment]
I will work on adopting the method outlined in the README and try to keep the batches smaller. Thanks for your answers.
