### ISSUE TITLE
--quick is slows down transcode

### ISSUE THREAD

**Issue by mikaelmoutakis** [donmelton/video_transcoding#315]
if I run transcode-video with "--encoder nvenc_h264" I get between 500-1000 fps on my machine when encoding dvd-rips. If I add the "--quick" option, the framerate drops to 200-300 fps. Not the behavior I would have expected. 

video_transcoding is a great piece of software by the way. I'm super impressed by the resulting video quality.

**Comment by donmelton** [comment]
@mikaelmoutakis Thanks for using my software and I'm glad it's working well for you.

The behavior you're seeing is because the `--quick` option requires the `x264` software video encoder. So adding `--quick` on the command line overrides any previous `--encoder` option you might have used. This is by design.

If you want to use the `nvenc_h264` encoder, then don't use `--quick`. It's not necessary.

BTW, if you prefer the speed of hardware encoders, then you might want to try my new project, "Other Video Transcoding" available here:

https://github.com/donmelton/other_video_transcoding

Unlike my older "Video Transcoding" project, the `other-transcode` tool in this package automatically selects a platform-specific hardware video encoder rather than relying on a slower software encoder.

**Comment by mikaelmoutakis** [comment]
Thank you for the quick reply! And I will check out "other video transcoder".  But I find it confusing and illogical that adding a "quick" option slows down the encoding. In my opinion, it would have been better if transcode-video ignored the --quick option when "encoder" is set, or threw an error.

**Comment by donmelton** [comment]
@mikaelmoutakis I'll consider adding a warning then. Thanks for your feedback!

Shall we consider this issue closed then?

**Comment by mikaelmoutakis** [comment]
Yes! :-)
