### ISSUE TITLE
Correct Dolby 2.0 Surround transcoding

### ISSUE THREAD

**Issue by phil4k** [donmelton/video_transcoding#316]
Hi,

I'm wondering if anyone can clear up some confusion I have with regards to transcoding a Dolby 2.0 Surround source or clarify my understanding of how the Apple TV HD deals with this type of source.

I have the 2006 Limited Edition Star Wars DVDs with the original theatrical versions. If I play the theatrical version on my blu-ray player my AV receiver (using Auto mode) indicates that it is receiving a Dolby Digital signal and Dolby Pro Logic II decoding is enabled. The display indicates Front L and R channels plus XC (Described as the mono surround channel or matrix encode flag).

Extracting the theatrical title from the DVD through MakeMKV provides a container with an AC-3 audio track.

If I use a typical command to transcode the video:
transcode-video —mp4 —crop 0:0:0:0 —burn-subtitle [num] <filename>
The tools produce an mp4 with a single AAC audio track. When this is played from my iTunes library via my ATV HD my AV receiver (using Auto mode) indicates Stereo on the display and playback of a PCM signal (I understand that tvOS by default sends a PCM stream). Does this transcode of the original AC-3 Dolby 2.0 Surround source still carry the matrix encode information? If DPLII is activated manually is this the same audio experience as with the blu-ray player?

If I copy the AC-3 track instead of transcoding my AV receiver will still indicate a Stereo source etc as above. Is this any improvement over the AAC audio track?

I assume that the lack of auto switching on the AV receiver when playing back MP4 files is related to the ATV HD and not directly related to the audio track in the file?

I hope that's clear and someone wouldn't mind clarifying how this works to give me a little peace of mind that my transcodes are the best quality possible from the source DVDs.

Thanks

Phil

**Comment by donmelton** [comment]
@phil4k This is a very interesting question. Unfortunately, I can't give you a definitive answer. But here's what I know and suspect...

Your original stereo track in AC-3 format will always be superior to a transcoding. And that original track is guaranteed to retain its Dolby Pro Logic II mix, even if your playback system doesn't recognize it.

Transcoding your stereo AC-3 track to AAC format should also retain the original Dolby Pro Logic II mix provided that you're using the default mixdown of `transcode-video` which is, basically, no mixdown at all. So that transcoded track should be in DPL II format as well. I've tested this myself and it seems to work.

I'm not sure why your AV receiver doesn't recognize the copied or transcoded tracks as being in DPL II format but I also suspect your Apple TV is the culprit here. But I don't have an Apple TV so I can't verify that suspicion.

Does that help?

**Comment by phil4k** [comment]
Hi Don,

Thanks that certainly helps ease my mind that the transcodes should have the matrix encoded audio retained.

Great tools btw, thanks for making them publicly available.
