### ISSUE TITLE
Multiple inputs into one output?

### ISSUE THREAD

**Issue by luminose** [donmelton/video_transcoding#33]
For a movie that spans multiple DVD/Blu-Ray discs, there a way to specify multiple inputs to be converted (merged) into one output? My current process is to use MKVtoolnix to merge the multiple MakeMKV outputs into one large MKV before conversion.

**Comment by donmelton** [comment]
@luminose No, there's no way to do that because `HandBrakeCLI` doesn't have a mechanism for that either. Sorry about that.

However, if the HandBrake developers decide to add such a feature, I'll consider adding to `transcode-video`.

I could do it by calling `mkvmerge` for you, but that would make assumptions about temporary storage for the merged file and such. And I don't want to do that considering the file sizes required.
