### ISSUE TITLE
Convert hevc (x265) video to mp4 not working

### ISSUE THREAD

**Issue by YannickGagnon** [donmelton/video_transcoding#39]
Hi, I', trying to convert an hevc video file to mp4, but the command complains about not finding any h264 track, is there a way to tell it to search for h265 or havoc?

Thanks,

**Comment by donmelton** [comment]
@YannickGagnon The `convert-video` tool requires input with AVC/H.264 video. That's by design.

The `transcode-video` tool will accept HEVC/H.265 video. Of course, that video transcoded.

Is this a feature request for HEVC/H.265 support? If so, that is my long-term plan. However, I haven't done so yet because HEVC/H.265 transcoding is so slow as to be unusable for most people and player support of the format is currently so limited.

**Comment by YannickGagnon** [comment]
@donmelton HEVC/H.265 works fine with Plex server :). I do use HEVC/H.265 primarily to save space keeping same quality as previously ripped H.264 files.

Looking forward H.265 support :+1:

**Comment by donmelton** [comment]
@YannickGagnon Yes, Plex has supported HEVC/H.265 in their server and desktop player since last year, I think. Do you have a device like Roku or Chromecast which supports it? Otherwise Plex server will transcode it to AVC/H.264.

**Comment by YannickGagnon** [comment]
I currently don't, but I don't really mind live transcoding until I get devices that actually support it.

Forward thinking I guess :)

**Comment by sunshying** [comment]
HandBrake could help convert HEVC into MP4 with H.264 codec or MPEG 2/4. 
![hevc-to-mp4](https://cloud.githubusercontent.com/assets/15936023/25113819/b12f52fc-242c-11e7-9dd1-6d1c3f6500e4.jpg)

Here's the free steps on HB HEVC TO MP4: [https://www.winxdvd.com/resource/fast-hevc-to-mp4-converter-free-download.htm](url)
