### ISSUE TITLE
Create output directory when it does not exist

### ISSUE THREAD

**Issue by sashkab** [donmelton/video_transcoding#47]
I've run batch conversion on a folder, where I have couple files and got following output:

```
$ for i in *.mkv; do
    convert-video -o out/ ${i}
done

/usr/local/bin/convert-video: not a directory: out/
Try `/usr/local/bin/convert-video --help` for more information.
```

Why can't output directory be created if it does not exist?

**Comment by donmelton** [comment]
@sashkab Unix-style command line tools normally do not create the output directory if it doesn't exist as a precaution against misspelling. For example, creating "/Volmuse/output" (instead of "/Volumes/output") would not only be a very bad idea but likely produce a misleading error message.

Seriously, just modify your script to do this:

```
for i in *.mkv; do
    mkdir -p out
    convert-video -o out/ ${i}
done
```

...and that should do the trick.
