### ISSUE TITLE
Why handbrake 0.10.0?

### ISSUE THREAD

**Issue by cadeon** [donmelton/video_transcoding#51]
I'm running CentOS 7, and the newest HandBrake-cli I can get out of a repo is 0.9.9. I can build a newer version, but that's... well it's painful in the environment I'm in. 

Is there any reason for 0.10.0, or will 0.9.9 work in most cases? Is there a way to avoid the version check?

**Comment by donmelton** [comment]
@cadeon My tools require `HandBrakeCLI` version 0.10.0 or later because bug fixes in that update solved problems that myself and other users kept having. The only way to avoid the version check is to modify the source code of my tools. However, my code may fail because it parses the diagnostic output of `HandBrakeCLI` and the format of that output changed in version 0.10.0.

Version 0.10.0 was released over a year ago. I'm surprised CentOS hasn't updated their repositories. But I can't really go back at this point. I'm sorry.
