### ISSUE TITLE
Passing Argument/Setting to HandbrakeCLI

### ISSUE THREAD

**Issue by dh007** [donmelton/video_transcoding#53]
In learning/applying the transcode-video tool, I saw that the DVD that was being transcoded was being done with h264 level 3.0; I was wondering if you could elucidate why that setting was chosen and if there is a way to pass a setting of 4.1 for example to HandbrakeCLI. For example, is the level for a Blu-Ray automatically 4.1? I tried a few combinations after reviewing the HandbrakeCLI and transcode-video --fullhelp and --help to pass the setting directly; I met with no success.

Thoughts?

**Comment by donmelton** [comment]
@dh007 Good questions! And opening an issue here is the perfect way to get them answered. Thanks.

When using the default settings, my `transcode-video` tool lets `HandBrakeCLI` choose the H.264 encoder level automatically. These automatic level selections are based on resolution of the output video.

When using some options, e.g. certain presets, my `transcode-video` tool forces an H.264 encoder level appropriate for the output video resolution, i.e. the same encoder level if you hadn't specified that option.

Why does `HandBrakeCLI` choose level `3.0` for DVD video instead of `4.0` or `4.1`? Because that's all that necessary. Increasing the level won't improve video quality at those resolutions. And level `3.0` ensures proper playback on more devices, especially older hardware.

And for 1080p or Blu-ray video, why does `HandBrakeCLI` choose level `4.0` instead of `4.1`? For similar reasons, but mostly for playback compatibility on certain devices. Forcing level `4.1` could allow peak bitrates to exceed what some devices are capable of handling.

Although the original H.264 video on a Blu-ray disc must be level `4.1`, its maximum bitrate must also be limited to 40,000 Kbps. This is much lower than what's actually allowed for "legal" level `4.1` video, that being 62,500 Kbps. And bitrates that high are typically only playable by more capable hardware like desktop CPUs or specialized decoder chips.

The maximum bitrate of H.264 level `4.0` video is limited to 25,000 Kbps. Since the rate control system in `transcode-video` sets the output bitrate target for 1080p video to 8,000 Kbps, it's unlikely that 25,000 Kbps limit is typically reached. So, increasing the level to `4.1` is of little, if any, benefit.

However, if you want to explicitly set the H.264 encoder level with `transcode-video`, e.g. to `4.1`, you can do that very easily with a command line like this:

```
transcode-video --handbrake-option encoder-level=4.1 "/path/to/Movie.mkv"
```

I'm closing this issue now but feel free to continue our conversation here with more comments and questions. Thanks, again!
