### ISSUE TITLE
Allow the user to change audio metadata language.

### ISSUE THREAD

**Issue by cnrd** [donmelton/video_transcoding#57]
This is already available when using MakeMKV, but I sometimes forget to add the correct language tag for the audio tracks. This can especially be a problem when ripping in multiple languages and still wanting to be able to see if the file contains English or local audio.

This means that I have to do one of two things currently:
Rip another copy with MakeMKV
Change the metadata using another tool before or after converting.

What I would like to be able to do:
If I find that I forgot to tag the file in MakeMKV, I would love to just be able to pass a parameter to transcode-video that would add the metadata language tag (I'm pretty sure handbrake have this?)

This would also enable me to just ignore the language tag in MakeMKV (Which is quite time consuming to actually do) and batch convert a bunch of movies that I know is in the same language, just passing the parameter for every file.

**Comment by donmelton** [comment]
@cnrd Actually, I believe you can change the language tag after the fact for a MKV file by using the `mkvpropedit` tool. There's no need to rip another copy via MakeMKV.

Let me know if you need a sample command line for that.

Unfortunately HandBrake doesn't have the capability to set the tag so I would have to post-process the output within `transcode-video` and `convert-video`. I'm not quite sure how to do that for MP4 files.

**Comment by cnrd** [comment]
This is how I do it for MP4:

`mp4track --track-id=2 --language eng [MP4FILE]`

When setting english as language.
My current sample of files shows that track-id 2 is always the audio track, but:

`mp4track --list [MP4FILE]`

will also return the type, sample below:
```

track[0] id=1
  type           = video
  enabled        = true
  inMovie        = true
  inPreview      = false
  layer          = 0
  alternateGroup = 0
  volume         = 0.0000
  width          = 1920.00000000
  height         = 1080.00000000
  language       = English
  handlerName    = VideoHandler
  userDataName   = <absent>
track[1] id=2
  type           = audio
  enabled        = true
  inMovie        = true
  inPreview      = false
  layer          = 0
  alternateGroup = 1
  volume         = 1.0000
  width          = 0.00000000
  height         = 0.00000000
  language       = English
  handlerName    = SoundHandler
  userDataName   = <absent>
```

The other problem I found with this is that the file will then need to be optimized for streaming (Moving the MOOV atoms):

`ffmpeg -i [MP4FILE] -c:v copy -c:a copy -movflags +faststart -o [NEWFILE]`

Whenever I try to change the metadata for MKV files, Plex does not pick it up, does it do that for you? If so, I would love to see your sample command!

**Comment by donmelton** [comment]
@cnrd And this is exactly why I always output MKV instead of MP4. :) So typical that changing the metadata would cause this kind of problem in that format. What a pain in the ass.

For Plex to pick up the change to your MKV files, you need to make sure and update your library. The re-scan should catch that. I haven't had a problem so far. (Of course, writing that will probably jinx it. :)

**Comment by donmelton** [comment]
@cnrd OK, after thinking about it some more, the functionality you're requesting is really outside the scope of `transcode-video` -- it's not a metadata editor. Since there are existing tools that you can use to correct your source material (even if the process for an MP4 is a little stupid) then I'm going to say "no" to this.

But, hey, keep the requests and ideas coming!
