### ISSUE TITLE
H.265 Support

### ISSUE THREAD

**Issue by dgibbs64** [donmelton/video_transcoding#59]
I am seeing H265 is becoming very popular (and I can see why). Do you think H265 support could be added? I think moving forward I would like to start using H265 (after running a few more tests) as it looks like I can achieve up to around 50% size reduction with no noticeable quality loss. It appears it will become the new standard in the next few years.

After moving house I will be setting up my HP server probably with VMware and having a new ubuntu 16.04 VM dedicated to automatically converting and transcoding using my automated bash scripts and your scripts. Im looking forward to getting this set up.

**Comment by donmelton** [comment]
@dgibbs64 Sorry I took so long to respond. I've been away all day.

There are several issues preventing me from supporting H.265, particularly the x265 encoder included with HandBrake, for the time being.

First, transcoding any quality (e.g. applying even only the `medium` preset) with x265 is even slower than using the `slower` preset with x264. That's just not practical for home transcoding. Speed is improving but, ironically, progress is slow.

Second, I'm not buying the 50% reduction in size without quality loss. I'm not seeing that with all the tests I've done so far. Plus, the x265 encoder is very prone to contouring and color banding. One reason for that is the low bitrates its trying to achieve. Don't get me wrong, x265 shows promise. But it's not ready yet.

Third, and most important, my default ratecontrol system can't be applied with x265. That's because x265 doesn't allow access to `qpmax`, a critical control to prevent degradation in quality. There's a bug open on x265 about this now. I've commented extensively on that bug. But no progress has been made so far. I'm starting to believe the only way to get the essential access to `qpmax` is to implement it myself and submit a patch to the x265 development team.

**Comment by donmelton** [comment]
@dgibbs64 BTW, something I forgot to mention: hard disk storage is cheap and getting cheaper right now. :)

**Comment by dgibbs64** [comment]
Good answer. Im glad I asked this. I can confirm I ran a test myself using anydvd software. I left a 40 min video converting to H.265 overnight it was still going 8 hours later. So yeah H.265 is not practical yet. Also looks like too many devices are not yet fully compatible or can't handle H.265 well currently. 

So it looks like a few more years and this may be the way forward but not yet.

Thanks again for taking the time to answer this :D. Maybe this should be a footnote on your readme as it may interest people.

**Comment by donmelton** [comment]
@dgibbs64 That's actually something I would rather include in a FAQ document rather than the current too-large README. And as soon as I get around to creating the Wiki here, I'll do that. Thanks.

**Comment by donmelton** [comment]
@dgibbs64 I'm actually going to re-open this issue because it's useful for others to read until the FAQ is online. Plus, they may disagree with us. :)

**Comment by terveer** [comment]
I do :)

A few weeks ago I've swapped my haswell core i7 for a new 6th series Intel NUC with a Skylake i5. 
That's the first CPU which encodes h.265 in hardware - and boy does it fast!

The visual differences between QSV and software encoding are perceivable but noticeably smaller than they've been for h.264. 

Still figuring out the sweet spot but currently I'm going for CBR 27 [really!] and convert HDA to E-AC3 (Dolby Digital Plus, since it allows 1536 kbit vs 640 kbit). 
This has acceptable quality for mediocre films, the files remain below 4GB (can be used easily with FAT32 drives) and the Skylake gets it done in realtime (60-80 minutes per encoding). 

I appreciate your input on qpmax yet still hope we we'll get h.265 some day ;)

**Comment by donmelton** [comment]
@terveer Hardware transcoding for H.265 isn't an option with HandBrake yet which my tools require. And my special ratecontrol system definitely wouldn't work with any hardware transcoding API that I've seen so far, whether it's H.265 or even H.264. A pity. But I'm glad your new hardware is working for you.

**Comment by donmelton** [comment]
@terveer BTW, hardware encoders are typically designed for realtime video chat or other similar duties. To maintain that performance, they often take many shortcuts with video quality. This is often by reducing reference frames, sub-pixel motion estimation, etc. so much that it would be the equivalent of using the `veryfast` preset with a software encoder. This is certainly the approach with Intel QSV. I don't know whether Intel's hardware H.265 encoder does something similar, but you might want to look closer at the output.

**Comment by donmelton** [comment]
@dgibbs64 OK, I've added a new "FAQ" section and answer to the "README" document explaining the status of H.265 support:

https://github.com/donmelton/video_transcoding#when-will-you-add-support-for-h265-video

So, I'll close this for now.

**Comment by dgibbs64** [comment]
Nice one!

**Comment by donmelton** [comment]
@dgibbs64 Thanks. I'll keep an eye on it and keep bugging the x265 folks, too. I'm hopeful they fix it sometime this year. If not, I may have to try my hand at patching it.

**Comment by Mangoes** [comment]
x265 now allows qpmax and qmin.

_x265 2.0+11
Gopi Satykrishna Akisetty rc: add qpmin and qpmax options 2016-07-15_

[Issue #232](https://bitbucket.org/multicoreware/x265/issues/232/add-option-to-specify-qpmax) is resolved.

Looking forward to the x265 support in video_transcoding.

Thanks.

**Comment by donmelton** [comment]
@Mangoes Yeah, I got the notification last week, too. :) Now we just wait for the HandBrake developers to release a version with that feature so I can test it.
