### ISSUE TITLE
query-handbrake-log ratefactor fails if the number it's searching for is less than 10

### ISSUE THREAD

**Issue by bmhayward** [donmelton/video_transcoding#61]
When using the "r" switch with the query-handbrake-log command to process a directory of log files, query-handbrake-log stops processing if no rate factor data is found in a log file. query-handbrake-log will acknowledge the failure in the Terminal, but no data is output.

Attached is a sample log file that does not process correctly with query-handbrake-log r.

It would be nice if query-handbrake-log were to note the issue to Terminal, but continue processing, leaving the rate factor value blank if none is found.

If you need anything else, please let me know.

Thanks,
Brent

[+FUTURAMA_S00E13#Even More Outtakes_t08.m4v.log.zip](https://github.com/donmelton/video_transcoding/files/235164/FUTURAMA_S00E13.Even.More.Outtakes_t08.m4v.log.zip)

**Comment by donmelton** [comment]
@bmhayward Good point on continue to process. I'll take a look at the code tonight and verify why it's doing that.

And thanks for the sample! I have no idea yet why it's failing because the `time`, `speed` and `bitrate` queries work fine and the file clearly contains the string "Avg QP: 9.77" which the regular expression should find. So, stay tuned on this one...

**Comment by donmelton** [comment]
@bmhayward OK, I see the bug on why `query-handbrake-log` failing to find the string "Avg QP: 9.77" in the file. And it's really funny, too. :)

In a way, this is a side effect of my new ratecontrol system that went into version 0.6.0. Because, until then, it was not really possible to get an average QP value from transcoding that was... wait for it... in single digits! :)

I actually thought about this case ahead of time (single digits, I mean) and baked it into the regular expression I use to find the string. However, what I didn't realize at the time because I didn't have a test case, is that HandBrake puts a space in front of the single digit if that happens. Yep, I'm not expecting the space between the ":" and the "9". Just shoot me.

But that will be easy to fix. And I'll do that in my next release.

However, changing the behavior to continue processing other files on failure is much harder. I'll need to think about that for awhile and consider whether it's worth it to make such a big change.

**Comment by donmelton** [comment]
@bmhayward BTW, an average P-frame quantizer, i.e. ratefactor, that low means you might want to transcode that file using the `--small-video` option since it doesn't really need all the extra bitrate. Just a thought.

**Comment by bmhayward** [comment]
Don,

Thanks for all the help!

I have been just using the defaults with transcode-video. I’ll look at using the —small-video option.

I am working on a tool that takes all the log files in a directory merges them into a single spreadsheet for easier viewing. That’s how I discovered the issue.

Thanks again for all your great work!

Best regards,
Brent

**Comment by donmelton** [comment]
@bmhayward You are very welcome, sir! And if you get that tool done, we would all love it if you share it on your GitHub account.

**Comment by donmelton** [comment]
@bmhayward BTW, I've been thinking about adding an option to `query-handbrake-log` so you can set the separator between the two fields, i.e. between the numerical data and the filename. For example, your could set the separator to a comma (",") or a tab character. Would that be useful to you and the tool you're building?

**Comment by donmelton** [comment]
@bmhayward Also, I just looked the output bitrate of your file and it's only `1006.30 kbps` so, I take it back, using `--small-video` probably won't make that much of a difference. Your mileage may vary.

**Comment by bmhayward** [comment]
Don,

It’s done!

I plan on posting it as part of an entire ingest/outgest workflow tool that I built around transcode-video. So far, over 300 DVD/Blu-rays transcoded using the workflow and transcode-video.

I’ll let you know when I post it to github!

Best regards,
Brent

**Comment by bmhayward** [comment]
Don,

Adding the option to set the separator between fields would be a tremendous help. Right now the tool goes through a bunch of gymnastics to put a separator in so that Numbers can read the finished file.

Best regards,
Brent

**Comment by donmelton** [comment]
@bmhayward Cool. Thinking about it again, a comma might not be that useful since filenames sometimes also have commas. The tab character would work much better. Is that what you use for importing into Numbers.app?

**Comment by hughker** [comment]
@donmelton not to hijack @bmhayward but I recently converted some 900+ Movies from AVI + MKV to MP4 for Plex using your tool and while it took awhile (even on a EC2) it all worked flawlessly, so thank you for making such a helpful tool. Now I just have to convert another 1200+ TV shows from AVI + MKV to MP4 but I don't think I'll be using EC2 for that this time around (:money_with_wings:)…

As for what to use as a separator, would a semicolon not work?

**Comment by donmelton** [comment]
@hughker You are very welcome, sir! Yes, time for a hardware upgrade. All that transcoding can be tiring. :)

Hmmm, that's a good point. Although the semicolon can appear in filenames, it's rare. And it begs the question, what are the other viable separator characters?

**Comment by donmelton** [comment]
@hughker @bmhayward Of course, I could change the default separator to the tab character and allow you to set it back to a space, semicolon, comma, etc. like the Unix `cut` command does with an option. The help text for it might look something like this:

```
    --delimiter STRING
                    use string as field delimiter (default: tab character)
```

Thoughts?

**Comment by bmhayward** [comment]
Don,

Tab is what I am converting a space from using the cut command. It takes a little bit of work as you need to first remove the fps, kbps, etc. columns from the file to get to two columns. From there you can use the join command to merge files.

Best regards,
Brent

**Comment by donmelton** [comment]
@bmhayward Ah, that's right. You would need to remove the labels as well. Silly me. Perhaps a `--delimiter` option is the wrong approach then. Maybe I should just leave the default as is and make a `--tabular` option (or something with a better name) that substitutes a tab for the space and removes the labels, essentially doing all that work for you. Would that work better?

**Comment by donmelton** [comment]
@bmhayward @hughker BTW, I'll probably release 0.8.1 with the actual `query-handbrake-log` bug fix maybe as early as this week and save the new option for 0.9.0.

Even though the bug fix is simple (and essentially done already), I'll hold up the ".1" release a few days just in case another user finds something else stupid that I've done in the 0.8.0 release that went out on Sunday. Also, believe it or not, many users don't like it when I release too often. Go figure. :)

Since the new `query-handbrake-log` option would an API change, that will need to go in the next "big" release. And I'm already working on some more audio API changes to `transcode-video` that will take at least a week or more to get the code right and get thoroughly tested. And it makes sense for those to all go in the 0.0. release.

**Comment by donmelton** [comment]
@bmhayward Here's the patch for the bug fix if you want to try it yourself:

```
diff --git a/bin/query-handbrake-log b/bin/query-handbrake-log
index 2722370..1ef44c4 100755
--- a/bin/query-handbrake-log
+++ b/bin/query-handbrake-log
@@ -213,7 +213,7 @@ HERE
           else
             Console.debug ratefactor_line
 
-            if ratefactor_line =~ /Avg QP:([0-9.]+)/
+            if ratefactor_line =~ /Avg QP: ?([0-9.]+)/
               report << "#{$1} #{video}"
             else
               fail "ratefactor not found: #{log}"
```

Yep. It's a two-character change. I just love those. :)

**Comment by bmhayward** [comment]
Don,

Thanks again for all the work! I'll have some time tomorrow to give this a go and report back.

**Comment by donmelton** [comment]
@bmhayward Cool. Just let me know. And, thanks!

**Comment by bmhayward** [comment]
Don,

Tested the change, works like a champ!
I've attached a sample output file. Any suggestions would be appreciated.

Going back to the API changes, that is what I was thinking, "just leave the default as is and make a --tabular option (or something with a better name) that substitutes a tab for the space and removes the labels."

Also, my misunderstanding of the original issue negates the thought that query-handbrake-log continue after an error. In that situation, it makes sense to throw the error and stop.

Thanks again,
Brent
[transcodeLogAnalysis.zip](https://github.com/donmelton/video_transcoding/files/239052/transcodeLogAnalysis.zip)

**Comment by donmelton** [comment]
@bmhayward Sorry, I've been AFK all day.

Thanks for testing! I'll probably release 0.8.1 with this change Thursday evening (my time).

That's some interesting data. Looks like you have a few episodes of "Futurama" that dip below a ratefactor of 10. But their bitrates are also appropriately low. I would expect that with classic "flat" animation.

I didn't have any problem importing that into Numbers.app. Worked perfectly and it was easy to read. I only wish Numbers.app made it simple and obvious to make column headings sortable. Oh well.

Also, I'll open a new issue soon for the `--tabular` enhancement and make sure you and @hughker know about it so you can comment. God willing one of us comes up with a better name than `--tabular` but that'll do for now. :)

**Comment by donmelton** [comment]
@bmhayward @hughker OK, version 0.8.1 was just released with this fix. Just `gem update video_transcoding` to get it. Thanks, again!

And I'll open a new issue tonight for the feature enhancement.
