### ISSUE TITLE
Add MakeMKV settings screenshots to README

### ISSUE THREAD

**Issue by agrajag9** [donmelton/video_transcoding#75]
Unfortunately the help for MakeMKV is lacking at best. It would be extremely helpful to see not just read an example of your settings for MakeMKV when you rip a Blu-Ray.

**Comment by donmelton** [comment]
@agrajag9 I would certainly agree that the documentation for MakeMKV is sparse, at best. However, the focus for my tools, and their README file, is on transcoding and not ripping. I've even considered removing the whole "Preparing your media for transcoding" section in the "Guide" since I think it's distracting. So I'm very hesitant to expand it at this point.

Properly explaining MakeMKV -- or even my particular settings -- could easily double the size of the existing README file. Especially when it comes to handling subtitles. That's because every disc is different. So my settings change all the time.

Is there a particular use case that you need help with? I can try to answer your questions here.

**Comment by bmhayward** [comment]
@agrajag9  take a look at this MakeMKV [documentation](https://github.com/bmhayward/Transcode#guide) I generated. It may provide some guidance with setup for a Blu-Ray rip.

**Comment by agrajag9** [comment]
@bmhayward excellent writeup! This answers most of my questions.

The only outstanding questions are about subtitles. I don't think I actually understand the "forced" subtitles thing. What's the difference between the following:

1. Selecting the parent but not the "forced only" child
2. Selecting the "forced only" child but not the parent
3. Selecting both the parent and "forced only" child

**Comment by bmhayward** [comment]
@agrajag9 all great questions. I have no idea what any of them do.
I use Plex exclusively for my media content distribution and rely on its built-in subtitle support.

Maybe @donmelton or someone else reading this thread has an idea of what these do.

**Comment by donmelton** [comment]
@bmhayward @agrajag9 OK, but you might not want to read this. :)

Subtitles are tricky. And it's impossible to know ahead of time exactly which subtitles contain embedded forced subtitles. This situation is further complicated because many discs are mastered incorrectly or, perhaps worse, mastered inconsistently in a boxed set—that can really make you crazy when you're ripping TV shows.

However, I have a very simple solution to this problem. But you may not like it …

Here's what I do, step by step:

1. Rip every subtitle track on the disc (or at least those tracks in your target languages). That means both the parent and child subtitles are checked in MakeMKV. Both of them, dammit! I'm serious.
2. Use a player like VLC or a tool like `mediainfo` to figure out which new subtitle tracks have been created in the output. These will (usually) be the embedded forced tracks.
3. Check (with VLC or `mediainfo`) to see if there is a  subtitle track that had its "forced" flag set by MakeMKV. You probably want to keep that track. But not always. This could be due to bad mastering. 
4. Decide which subtitle tracks to keep. Sometimes newly created child tracks are simply duplicated versions of the parent track. This is due to bad mastering. Just shoot me. And you probably don't want to keep those duplicates.
5. Remux the ripped MKV file with `mkvmerge` from MKVToolNix to exclude the subtitle tracks you don't want (and to set or reset the forced flag as needed).

Remuxing (not "remixing," dammit!) is not as hard as it sounds. And there is no other way to get the subtitle tracks you want without re-ripping the disc. Not only does that take a shitload longer, it's very prone to error.

So, that's it. Let me know if I can clarify anything for you.

**Comment by bmhayward** [comment]
@donmelton thanks!

**Comment by donmelton** [comment]
@agrajag9 With the cool documentation from @bmhayward and my cranky answer, I think we've answered the original question. So I'm going to close this issue for now. But feel free to keep commenting here. Thanks.

**Comment by hisaac** [comment]
This is a great rundown of answers I needed as well! Thanks y'all!

@bmhayward, maybe you could add subtitle steps @donmelton clarified to your documentation? It'd be nice to have it all in one place.

**Comment by bmhayward** [comment]
@hisaac let me see what I can do. I was thinking about potentially adding some of Don's suggestions to my workflow solution. Look for something in the next couple of weeks.
