### ISSUE TITLE
`--copy-audio-name all` copies track names for duplicate / converted tracks

### ISSUE THREAD

**Issue by faithfracture** [donmelton/video_transcoding#79]
Setting the copy-audo-name parameter to "all", if the main audio track is a surround track, results in the 2nd audio track (the one that automatically gets mixed down from surround to 2-channel AAC) having the same name as the first track.

For example, if I have a video with 2 audio tracks:
Audio 1 - Surround 5.1
Audio 2 - Commentary

and I use the `--add-audio all --copy-audio all --copy-audio-name all` parameters, the resulting mkv will have the following audio tracks:

Audio 1 - Surround 5.1
Audio 2 - Surround 5.1 (even though this track is actually a 2-channel stereo mix)
Audio 3 - Commentary

If I do not use `--copy-audio-name all`, the resulting audio tracks are named:

Audio 1 - Surround
Audio 2 - Stereo
Audio 2 - Stereo

Since (I think??) it is transcode-video that is creating the new 2 channel AAC audio track, I expect would expect it to inject an appropriate name for the file.

I know some folks may actually want the track name for the first multi-channel audio track copied over to the 2-channel mixed down one, so I might suggest adding an additional option to the `--copy-audio-name` parameter to not copy track names over for the newly created track. Something like `--copy-audio-name TRACK| all | existing` where the `existing` option only copies the track name if the track existed in the original container.

**Comment by donmelton** [comment]
@faithfracture This is, indeed, a limitation. But it was done for simplicity---both of implementation and API design.

Let me see if I can figure out a way of just "doing the right thing" for both types of users without having to modify the API. But your suggestion, i.e. adding "existing," is pretty simple.

**Comment by donmelton** [comment]
@faithfracture Sorry I took so long to get back to you on this. I suck.

OK, I've been noodling on this quite awhile today and I'm now not inclined to make this change, both for reasons of semantics and realizing it's not all that simple to implement either. Let me elaborate ...

When the main audio track, or any track that's set to `double` width, is created in the output file, neither track is "existing." Both tracks are essentially identical in content but only different in format. And the order of those two formats changes depending on whether your output file type is MKV or MP4. Meaning surround is first for MKV and stereo is first for MP4.

So, if the input track is named "Surround 5.1," using your suggested "copy the name to the first output track only" behavior is going to be wrong for the MP4 file. Of course, I could only copy the name to the surround track, no matter what order it's in. But what if the input track is named "Stereo" or something otherwise inappropriate? Then I'm doubly wrong and I've made things worse.

This now seems to me like an edge-case issue. And I am reticent to change the code or add API to address it. You're better served using a tool like `mkvpropedit` after transcoding to tweak track names.

My apologies for initially making you think this would be a simple problem to solve.

Anyway, I'm closing this now but feel free to comment again here.

**Comment by faithfracture** [comment]
Ok, that makes sense. This really only comes up for me when there is/are director or other commentary tracks I want to include. I’ve been using mkvpropedit to change the track names after conversion anyways. Thanks for taking a look into it though.
