### ISSUE TITLE
--title flag does not work when the input is the block device

### ISSUE THREAD

**Issue by timdream** [donmelton/video_transcoding#85]
Thank you for making this project! I've heard about you talked about it many times on Twitter or podcast interviews.

I have a disk that is probably damaged, so a simple `HandBrakeCLI --input=/dev/sr0 --scan` only outputs 1 title. However, title 2 does exist and I would like to have `transcode-video` to transcode that (as it couldn't identify the main feature it couldn't find).

The following command failed with `invalid title index: #2`:

    transcode-video --add-subtitle all --no-auto-burn --quick --title 2 --m4v /dev/sr0 -o "`lsblk -o label /dev/sr0 | tail -n 1`.m4v"

Yet if I mount the disk and do this:

    transcode-video --add-subtitle all --no-auto-burn --quick --title 2 --m4v /mnt/disk -o "`lsblk -o label /dev/sr0 | tail -n 1`.m4v"

everything would work.

I grep the error and found this:

https://github.com/donmelton/video_transcoding/blob/bf464d39e297310607531baf50e735338fa92ceb/lib/video_transcoding/media.rb#L19-L31

It seems that the code only allow title section if the input points to a directory. It should have allow *directories* and *block devices*, probably *disk images*.

I don't know if there is a easy way to figure out if a file falls into the later two. Should we just remove the directory check?

**Comment by donmelton** [comment]
@timdream You are very welcome, sir! I'm glad my tools are working out for you.

And, yes, you've found a limitation in the way my tools, particularly `transcode-video`, handle inputs. But this is an intentional limitation.

I explained the reason for not handling disk images as file inputs in the resolution to issue https://github.com/donmelton/video_transcoding/pull/21 if you want to review that. And the reason for not handling devices is similar. Device inputs would not only complicate the code, but it's entirely likely they would not work reliably across multiple platforms. That's a development headache I don't need.

Anyway, I don't think it's onerous to require mounting the device before scanning or transcoding from the directory.

Thanks, and keep the questions and ideas coming!

**Comment by timdream** [comment]
@donmelton Interesting. It doesn't seem obvious that block devices are not supported!

Depend on level of defense we want, do you think it should be simply mentioned in README, or actively detected and rejected? I can submit a pull request on either.

**Comment by donmelton** [comment]
@timdream So far, you're the first person that's reported this problem so I don't see it as a big deal. :) But if you can find a clean way to detect and reject block devices, please submit a pull request and I'll review it.

Thanks!
