### ISSUE TITLE
Multiple subtitle options as fallback

### ISSUE THREAD

**Issue by mushbuddygoose** [donmelton/video_transcoding#94]
Don -

First let me take opportunity to say these scripts are fantastic. You replaced a whole series of automator and hazel scripts I was using and the quality and ease of use is superb.

Would it be possible to allow multiple subtitle options such that i could first search for forced subtitles to burn-in followed by adding the main language subtitle? In my attempts to try this, if it didn't find forced subtitles it never added the English subtitles. 

I recognize this may not be possible as this is done by the handbrake script which may already be in process. But its more because i seem to have so many issues with forced subtitles being recognized by handbrake that i want it to fallback to adding the subtitles so they can still be turned on manually.

Unless you know how to alter the subtitle search parameters in the handbrake script which i then could build from source :)

Thanks again for all the hard work.

**Comment by donmelton** [comment]
@mushbuddygoose Sorry I took so long to reply. I've been on the road traveling today due to a family emergency.

You are very welcome for the tools! I'm glad they're working out for you.

Could I ask which subtitle options and arguments you are using now? Would this be `--burn-subtitle scan` or `--force-subtitle scan`?

Thanks.

**Comment by mushbuddygoose** [comment]
here is my script i run (the  $1 is cause i use hazel):transcode-video $1 --m4v --crop detect --fallback-crop handbrake --burn-subtitle scan --add-subtitle 1

**Comment by donmelton** [comment]
@mushbuddygoose Sorry I took so long to reply.

Unfortunately, I can't implement fallback options after calling HandBrake to scan forced subtitles. This is because it's impossible for me to know whether HandBrake found a forced subtitle until transcoding is complete. And by then it's too late. The process is, as you guessed, opaque to my `transcode-video` tool.

Sorry about that.

I'll close this now but feel free to continue commenting.
